import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const ANUSUHU_SEDID_PART1_FILES: DriveFile[] = [
    {
        id: 'anusuhu-sedid-1-pdf',
        name: 'አኑስሁ ሰዲድ part 1.pdf',
        type: 'pdf',
        url: getDirectLink('1_N3ZAsGo7lZ3ui0ppDukzwyU7HNPXAaY'),
    },
    { id: 'anusuhu-sedid-1-1', name: 'አኑስሁ ሰዲድ part 1 ደርስ 1.mp3', type: 'audio', url: getDirectLink('15yLyveUEaYD7QgRfI4IuwUeWKr1dEF6f') },
    { id: 'anusuhu-sedid-1-2', name: 'አኑስሁ ሰዲድ part 1 ደርስ 2.mp3', type: 'audio', url: getDirectLink('10i_A2rA8xSVtYqEj1aJ77hhos0hHZVt7') },
    { id: 'anusuhu-sedid-1-3', name: 'አኑስሁ ሰዲድ part 1 ደርስ 3.mp3', type: 'audio', url: getDirectLink('1Cet2DKK_7jMhQJzEbYQvuA6-6275C0oP') },
    { id: 'anusuhu-sedid-1-4', name: 'አኑስሁ ሰዲድ part 1 ደርስ 4.mp3', type: 'audio', url: getDirectLink('17L2bytMUjXHP2sBBUkvyGOhCKCjur8Vd') },
    { id: 'anusuhu-sedid-1-5', name: 'አኑስሁ ሰዲድ part 1 ደርስ 5.mp3', type: 'audio', url: getDirectLink('16pDOYJs0m3RQj4vL95CMQeKYveCID-Yb') },
    { id: 'anusuhu-sedid-1-6', name: 'አኑስሁ ሰዲድ part 1 ደርስ 6.mp3', type: 'audio', url: getDirectLink('1BPH0MF-nOpWv2RMmSMfhMHLCXZNi-Mf3') },
    { id: 'anusuhu-sedid-1-7', name: 'አኑስሁ ሰዲድ part 1 ደርስ 7.mp3', type: 'audio', url: getDirectLink('1QjPO6BtkfLgfYsqmmdt_SrG_9sjw1NHP') },
    { id: 'anusuhu-sedid-1-8', name: 'አኑስሁ ሰዲድ part 1 ደርስ 8.mp3', type: 'audio', url: getDirectLink('1EN6DiX28XVaavl-d2wjymd5d-7upuEa7') },
    { id: 'anusuhu-sedid-1-9', name: 'አኑስሁ ሰዲድ part 1 ደርስ 9.mp3', type: 'audio', url: getDirectLink('161oiJU5t5VW8X-cpWVOU8mN_5hOIg_XU') },
    { id: 'anusuhu-sedid-1-10', name: 'አኑስሁ ሰዲድ part 1 ደርስ 10.mp3', type: 'audio', url: getDirectLink('159WpicUFk4jjhkPzCka5EH6HV3QMFVdr') },
    { id: 'anusuhu-sedid-1-11', name: 'አኑስሁ ሰዲድ part 1 ደርስ 11.mp3', type: 'audio', url: getDirectLink('1ntTff9q2v5m8cXI42unAK2o1oC8Sg1No') },
    { id: 'anusuhu-sedid-1-12', name: 'አኑስሁ ሰዲድ part 1 ደርስ 12.mp3', type: 'audio', url: getDirectLink('1RTCa4Hl-buz2R64JQQrff8O2V6oMy7wr') },
    { id: 'anusuhu-sedid-1-13', name: 'አኑስሁ ሰዲድ part 1 ደርስ 13.mp3', type: 'audio', url: getDirectLink('1uAlheOtMuP6RE86fRw_ed_OsCZIV6c1b') },
    { id: 'anusuhu-sedid-1-14', name: 'አኑስሁ ሰዲድ part 1 ደርስ 14.mp3', type: 'audio', url: getDirectLink('10YxfQ36ohbW1lizlUgCw6f4O7FVNB4VB') },
    { id: 'anusuhu-sedid-1-15', name: 'አኑስሁ ሰዲድ part 1 ደርስ 15.mp3', type: 'audio', url: getDirectLink('154filHl6M2U6H36Ei9k1w40sGlKNj3Fi') },
    { id: 'anusuhu-sedid-1-16', name: 'አኑስሁ ሰዲድ part 1 ደርስ 16.mp3', type: 'audio', url: getDirectLink('1KPF1gkE-sqONimojemX9dHDWTfw17w1s') },
    { id: 'anusuhu-sedid-1-17', name: 'አኑስሁ ሰዲድ part 1 ደርስ 17.mp3', type: 'audio', url: getDirectLink('1ycFbotiMQOFmtFFEBsRgjGe6Qng1B44H') },
    { id: 'anusuhu-sedid-1-18', name: 'አኑስሁ ሰዲድ part 1 ደርስ 18.mp3', type: 'audio', url: getDirectLink('1Ssq_ECkl3mgREhgjHlmPt3W1nITW5_KF') },
    { id: 'anusuhu-sedid-1-19', name: 'አኑስሁ ሰዲድ part 1 ደርስ 19.mp3', type: 'audio', url: getDirectLink('1n_A3kQtvbb8cgeFUCDX6vrAmqnwXiJe5') },
    { id: 'anusuhu-sedid-1-20', name: 'አኑስሁ ሰዲድ part 1 ደርስ 20.mp3', type: 'audio', url: getDirectLink('1L53JEWSdZzAXW6yuZNjwYo3hl3spTQmF') },
    { id: 'anusuhu-sedid-1-21', name: 'አኑስሁ ሰዲድ part 1 ደርስ 21.mp3', type: 'audio', url: getDirectLink('1_H2177t5mlX2vMnRwGdzSczZ4eNzfAXB') },
    { id: 'anusuhu-sedid-1-22', name: 'አኑስሁ ሰዲድ part 1 ደርስ 22.mp3', type: 'audio', url: getDirectLink('1IByH_VvvKjtDv0qb6NLaGsBu_QMatXFi') },
    { id: 'anusuhu-sedid-1-23', name: 'አኑስሁ ሰዲድ part 1 ደርስ 23.mp3', type: 'audio', url: getDirectLink('1pcS7bO2A3TVBwx60i95zxGnYdF2CV09Z') },
    { id: 'anusuhu-sedid-1-24', name: 'አኑስሁ ሰዲድ part 1 ደርስ 24.mp3', type: 'audio', url: getDirectLink('1tHzcFW1SdSZFqP0jtUXcPyBV569iBmRC') },
    { id: 'anusuhu-sedid-1-25', name: 'አኑስሁ ሰዲድ part 1 ደርስ 25.mp3', type: 'audio', url: getDirectLink('1QKTlNTXkWrw_ACumeaKI2rNcwoVZ3IvW') },
    { id: 'anusuhu-sedid-1-26', name: 'አኑስሁ ሰዲድ part 1 ደርስ 26.mp3', type: 'audio', url: getDirectLink('1ukrE2ibKn0kO4BDgdk0NDQlfmFSrBWc_') },
    { id: 'anusuhu-sedid-1-27', name: 'አኑስሁ ሰዲድ part 1 ደርስ 27.mp3', type: 'audio', url: getDirectLink('159dtG8uyrKngHmN8yir3NvvuKTE_0yso') },
    { id: 'anusuhu-sedid-1-28', name: 'አኑስሁ ሰዲድ part 1 ደርስ 28.mp3', type: 'audio', url: getDirectLink('1iVycvyvovBgopA9tHX5auo6klVh1DZQL') },
    { id: 'anusuhu-sedid-1-29', name: 'አኑስሁ ሰዲድ part 1 ደርስ 29.mp3', type: 'audio', url: getDirectLink('1J8366e5fm3cjZxjb2z7SGYF0Diy2F5JX') },
    // 30 is missing
    { id: 'anusuhu-sedid-1-31', name: 'አኑስሁ ሰዲድ part 1 ደርስ 31.mp3', type: 'audio', url: getDirectLink('1N_9DvyiQerqa0ZqcpvWm_DFhYGau2ApF') },
    { id: 'anusuhu-sedid-1-32', name: 'አኑስሁ ሰዲድ part 1 ደርስ 32.mp3', type: 'audio', url: getDirectLink('1lm4cEnrFvuPNw6k9gnGoM3iG1gsV8AYy') },
    { id: 'anusuhu-sedid-1-33', name: 'አኑስሁ ሰዲድ part 1 ደርስ 33.mp3', type: 'audio', url: getDirectLink('1jzYVpFXpBUA93A7rrwJHbUOdp4oazC8h') },
    { id: 'anusuhu-sedid-1-34', name: 'አኑስሁ ሰዲድ part 1 ደርስ 34.mp3', type: 'audio', url: getDirectLink('1VpZQHU12OnuHvkhdQagodOMnNQdqTG3o') },
    { id: 'anusuhu-sedid-1-35', name: 'አኑስሁ ሰዲድ part 1 ደርስ 35.mp3', type: 'audio', url: getDirectLink('13g_FV9-sduNykQtLnKriOdBexCmQgkdY') },
    { id: 'anusuhu-sedid-1-36', name: 'አኑስሁ ሰዲድ part 1 ደርስ 36.mp3', type: 'audio', url: getDirectLink('1nCrqD2kUdR7P-149q7DY-m7EoIp6eEIf') },
    { id: 'anusuhu-sedid-1-37', name: 'አኑስሁ ሰዲድ part 1 ደርስ 37.mp3', type: 'audio', url: getDirectLink('1F7t75gKF-pTCBibwlMud5nlRHeDaPN8W') },
    { id: 'anusuhu-sedid-1-38', name: 'አኑስሁ ሰዲድ part 1 ደርስ 38.mp3', type: 'audio', url: getDirectLink('1Wpm98L_Vt-pbrvqAvwxY2VVtpM5-MWEX') },
    { id: 'anusuhu-sedid-1-39', name: 'አኑስሁ ሰዲድ part 1 ደርስ 39.mp3', type: 'audio', url: getDirectLink('1sXjAb_QT14k7VkIApmHz9StVxLdaGlm4') },
    { id: 'anusuhu-sedid-1-40', name: 'አኑስሁ ሰዲድ part 1 ደርስ 40.mp3', type: 'audio', url: getDirectLink('1hYHhPzcNh8dEEy8zl3VhGYLNZ4nFV9XZ') },
    { id: 'anusuhu-sedid-1-41', name: 'አኑስሁ ሰዲድ part 1 ደርስ 41.mp3', type: 'audio', url: getDirectLink('1Y14z_D8VTcukDMJjkr3cSdRIsJVJ_xFY') },
];
