import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://docs.google.com/uc?export=download&id=${id}&confirm=t`;

export const BEYQUNYA_FILES: DriveFile[] = [
    {
        id: 'beyqunya-pdf',
        name: 'ሸርህ መንዙመቱል በይቁንያ.pdf',
        type: 'pdf',
        url: getDirectLink('1HFKiO8NjDZQzZTBY5xOt3PlNH7eKejG4'),
    },
    { id: 'beyqunya-1', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 1.mp3', type: 'audio', url: getDirectLink('1NFD18yYLy6ISJuV1lbR6o9m4pvNC7St0') },
    { id: 'beyqunya-2', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 2.mp3', type: 'audio', url: getDirectLink('1QeXRTC_8Lbjz-6h9oPgYsLjQnyAv63aH') },
    { id: 'beyqunya-3', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 3.mp3', type: 'audio', url: getDirectLink('1htAVkmKPOGxf_aG4rNt1ndyK0bmXh7je') },
    { id: 'beyqunya-4', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 4.mp3', type: 'audio', url: getDirectLink('1-bnOWr4GtBGf9QVIlXkmxXBkxF0f5Owe') },
    { id: 'beyqunya-5', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 5.mp3', type: 'audio', url: getDirectLink('1vjmXXKAxdLAd8lyHIAsqZxplOANVK1Ed') },
    { id: 'beyqunya-6', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 6.mp3', type: 'audio', url: getDirectLink('14wg7kalZOeXRM8t7iqpXj6Jgw7iusIQp') },
    { id: 'beyqunya-7', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 7.mp3', type: 'audio', url: getDirectLink('1sIdkZ_OkGseDxXv3Fea00RF0ORFzPVjn') },
    { id: 'beyqunya-8', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 8.mp3', type: 'audio', url: getDirectLink('1eAD4O6VLGRRusFrD3V21pad5RM2K8yr-') },
    { id: 'beyqunya-9', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1TQOoTtCpKyKUXO3JTpQsp8aa21EAket3') },
    { id: 'beyqunya-10', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1OutFlSOx-gB4okBmX074BkCMZvfy_4oh') },
    { id: 'beyqunya-11', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1jgwsEkauDs_2aT-h8-L5TyZ01ZnNqdvg') },
    { id: 'beyqunya-12', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 12.mp3', type: 'audio', url: getDirectLink('1WVG0-AhtHMSUnjoPfnbqeEzATtkiisbK') },
    { id: 'beyqunya-13', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 13.mp3', type: 'audio', url: getDirectLink('1N3xqHwClBcS156T6D602Bf0AnBjOLT64') },
    { id: 'beyqunya-14', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 14.mp3', type: 'audio', url: getDirectLink('1EPgKdrErJrqJ2BlcOhVaLmGp9NE7K_xE') },
    { id: 'beyqunya-15', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1DbOOrz7hrkNRlw1B6rcPi3-cpbc-I21I') },
    { id: 'beyqunya-16', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 16.mp3', type: 'audio', url: getDirectLink('1bhg_zkWduX2yph17wMBZo9uD-Y8d-81C') },
    { id: 'beyqunya-17', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1pHdqZLp4WuNFt9Izno9zLi6x6ZSB4m5w') },
    { id: 'beyqunya-18', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 18.mp3', type: 'audio', url: getDirectLink('12puhHdctpdmc2CpEbh8XHtemF37Hr88K') },
    { id: 'beyqunya-19', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 19.mp3', type: 'audio', url: getDirectLink('11Y1NR17v_MxretRrvElj9TQ9QYWlWS5Z') },
    { id: 'beyqunya-20', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 20.mp3', type: 'audio', url: getDirectLink('19iwMwqHiPzaVF4uqshomCrkxVq2E-K-z') },
    { id: 'beyqunya-21', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1DasiAPX8FcJaXzpTmTwGzjeIaiu_MYM0') },
    { id: 'beyqunya-22', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1tPeQRJV9ZjCxxdYiVxAjiKQvh9vBjhkA') },
    { id: 'beyqunya-23', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1ZfkqTEQC8O_3TA6lrXgV4K4NYHc_Trip') },
    { id: 'beyqunya-24', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 24.mp3', type: 'audio', url: getDirectLink('1fDuURJmNNO4Wb-EC5jV1PmvKqrnYDwjD') },
    { id: 'beyqunya-25', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 25.mp3', type: 'audio', url: getDirectLink('1_M3YCI7tZBLKc1tVQI_M3zOIkogIV3_l') },
    { id: 'beyqunya-26', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 26.mp3', type: 'audio', url: getDirectLink('11nKl2UtOPmqwWxzNF3a16uxGxOhHPjw1') },
    { id: 'beyqunya-27', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1zRqWVBSO1Bu_QKItHty5NfkjNsRZtmxn') },
    { id: 'beyqunya-28', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1hOQNqURINwsOF46QSvt2hHR8ZA998DMS') },
    { id: 'beyqunya-29', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 29.mp3', type: 'audio', url: getDirectLink('1p30uuotmUy0Wwifi6nxR3nZn4Jsc_7dW') },
    { id: 'beyqunya-30', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 30.mp3', type: 'audio', url: getDirectLink('18R2s-UdaHOc25ZOHllNV8EtBg-1yf6kE') },
    { id: 'beyqunya-31', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 31.mp3', type: 'audio', url: getDirectLink('1PW80dYEWUB49FbsnJwGW2mXK8hpAXNsU') },
    { id: 'beyqunya-32', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1_0BSj95776SSAeELqrI4V76OFO9KGG_Z') },
    { id: 'beyqunya-33', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 33.mp3', type: 'audio', url: getDirectLink('1YbCB4ONXxUqOX4p3e7ZSUsPcb-d4OHYq') },
    { id: 'beyqunya-34', name: 'ሸርህ መንዙመቱል በይቁንያ ደርስ 34.mp3', type: 'audio', url: getDirectLink('1VLQtyK82LaKplFiwmHLnxyRd4-CEF87Q') },
];
