import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const IRSHAD_FILES: DriveFile[] = [
    {
        id: 'irshad-pdf',
        name: 'ኢርሻድ.pdf',
        type: 'pdf',
        url: getDirectLink('1gsY3p0Vt9WA2mQGkGuJ8DrKFQ07PLshb'),
    },
    { id: 'irshad-2', name: 'ኢርሻድ ደርስ 2.mp3', type: 'audio', url: getDirectLink('12BjQT4V6d8lrmjCgzMyQarA-QMqVf1Rs') },
    { id: 'irshad-3', name: 'ኢርሻድ ደርስ 3.mp3', type: 'audio', url: getDirectLink('1_GCPeh9hZ740qB_aEO4KMgTDySURNGAm') },
    { id: 'irshad-4', name: 'ኢርሻድ ደርስ 4.mp3', type: 'audio', url: getDirectLink('126JulQ7By4DgksyMDiW9p86FDyesugOa') },
    { id: 'irshad-5', name: 'ኢርሻድ ደርስ 5.mp3', type: 'audio', url: getDirectLink('1RuPFQLvXcubeU-OVVOP1lof4hSdKKJq9') },
    { id: 'irshad-6', name: 'ኢርሻድ ደርስ 6.mp3', type: 'audio', url: getDirectLink('19WkyHQDBtmgAbBoTloBZnNLyQO5vOB9v') },
    { id: 'irshad-7', name: 'ኢርሻድ ደርስ 7.mp3', type: 'audio', url: getDirectLink('11a2Ba70rY9A8188tKGBTlgDSfGEvs4pq') },
    { id: 'irshad-8', name: 'ኢርሻድ ደርስ 8.mp3', type: 'audio', url: getDirectLink('1SXXBkwBpD04qnhF1oUIPz7TTys2YUDqg') },
    { id: 'irshad-9', name: 'ኢርሻድ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1wGiN1O3ImorqZk6GYDg4MV5u0J9l4UPk') },
    { id: 'irshad-10', name: 'ኢርሻድ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1qQLr2V9FWi96lbaGXyZ6-bMZ555t2SIj') },
    { id: 'irshad-11', name: 'ኢርሻድ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1R8fH2Z27HqdhhxwiQq55cXxmdEkR05au') },
    { id: 'irshad-12', name: 'ኢርሻድ ደርስ 12.mp3', type: 'audio', url: getDirectLink('1Y43fyFFks21A834nQjbsjHcMWiRry6B3') },
    { id: 'irshad-13', name: 'ኢርሻድ ደርስ 13.mp3', type: 'audio', url: getDirectLink('1EF60ESMffmgEP_Ty6xAh_4W27H-jTriW') },
    { id: 'irshad-14', name: 'ኢርሻድ ደርስ 14.mp3', type: 'audio', url: getDirectLink('1nH84tJdEtivPSREYBk4zr-Ome6KiUCDE') },
    { id: 'irshad-15', name: 'ኢርሻድ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1jA1ZuFcnEUsBwoT0ObsqUhHUSthCe6eh') },
    { id: 'irshad-16', name: 'ኢርሻድ ደርስ 16.mp3', type: 'audio', url: getDirectLink('1OH31DedcAecJ9d4mTv2vOnb9Q5KPDh40') },
    { id: 'irshad-17', name: 'ኢርሻድ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1JoadJLq0ASqe4AC7U-Jz8ZUVJ4EJ1KTu') },
    { id: 'irshad-18', name: 'ኢርሻድ ደርስ 18.mp3', type: 'audio', url: getDirectLink('1_-PXVgh5drpXdVqqkTMVmUckWkIiQ_R3') },
    { id: 'irshad-19', name: 'ኢርሻድ ደርስ 19.mp3', type: 'audio', url: getDirectLink('1g3iliIMrIE_1GsSFz-xCyXbwx709E3qF') },
    { id: 'irshad-20', name: 'ኢርሻድ ደርስ 20.mp3', type: 'audio', url: getDirectLink('1Ei3qXBrIOgXBXw6JG3_bl79pVSdg12nQ') },
    { id: 'irshad-21', name: 'ኢርሻድ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1JUe6Un-RLcPTqqDa7h-02HrecdELspSg') },
    { id: 'irshad-22', name: 'ኢርሻድ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1MRcKiqjSn63rtkXrSYFMMv44-9g43TUb') },
    { id: 'irshad-23', name: 'ኢርሻድ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1vL5uzAAeMuvCZJUbG5AsrbhNZ5AIGJI8') },
    { id: 'irshad-24', name: 'ኢርሻድ ደርስ 24.mp3', type: 'audio', url: getDirectLink('1kYyuy1gjmosV2pa8-Ccx7y3xyizDfgKq') },
    { id: 'irshad-25', name: 'ኢርሻድ ደርስ 25.mp3', type: 'audio', url: getDirectLink('15cuPap-F8xs8GJ_qMjzLKYKEFck-HBdT') },
    { id: 'irshad-26', name: 'ኢርሻድ ደርስ 26.mp3', type: 'audio', url: getDirectLink('1s8pR1lcpDUI_9EIbRZukcS38L8a_L7a8') },
    { id: 'irshad-27', name: 'ኢርሻድ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1rBf-BMQiALGEufm58NdhFzOJBkIpjXV9') },
    { id: 'irshad-28', name: 'ኢርሻድ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1_unH0Hbef8r2sDvHG964EiYWThVAauDx') },
    { id: 'irshad-29', name: 'ኢርሻድ ደርስ 29.mp3', type: 'audio', url: getDirectLink('15Ho-tPUTJmKzczRTMiQOW7Itc3ifEK2z') },
    { id: 'irshad-30', name: 'ኢርሻድ ደርስ 30.mp3', type: 'audio', url: getDirectLink('1cEW_YIWvxY4F4oA1W0yCsMpRf6jGGI5C') },
    { id: 'irshad-31', name: 'ኢርሻድ ደርስ 31.mp3', type: 'audio', url: getDirectLink('1Nwk6-Ul9WKOrgcVHov0ycdpybyura05H') },
    { id: 'irshad-32', name: 'ኢርሻድ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1tIi7N4RDRrpLHjtIF-ZxhRDlO5MkIzY6') },
    { id: 'irshad-33', name: 'ኢርሻድ ደርስ 33.mp3', type: 'audio', url: getDirectLink('1OC7sXEImck7nfncZqqWJRlT0bVr4d6e3') },
    { id: 'irshad-34', name: 'ኢርሻድ ደርስ 34.mp3', type: 'audio', url: getDirectLink('12ZUx4zGVjZ-6JoeZluJttBOwYWTKpv4C') },
    { id: 'irshad-35', name: 'ኢርሻድ ደርስ 35.mp3', type: 'audio', url: getDirectLink('1UrUnUCWkgjVc794moLhxVsdHaSKQ0UHJ') },
    { id: 'irshad-36', name: 'ኢርሻድ ደርስ 36.mp3', type: 'audio', url: getDirectLink('1eDlyPw6MPctbKBBaENA2vQH1o9Pc3i95') },
    { id: 'irshad-37', name: 'ኢርሻድ ደርስ 37.mp3', type: 'audio', url: getDirectLink('1xa84DMgsy3_-hAPutLoaBKXRgiPOhZkA') },
    { id: 'irshad-38', name: 'ኢርሻድ ደርስ 38.mp3', type: 'audio', url: getDirectLink('1ZNQVRliBJujWUgzwj_oWiLC0ze3ZqYef') },
    { id: 'irshad-39', name: 'ኢርሻድ ደርስ 39.mp3', type: 'audio', url: getDirectLink('1KjrR8CyhKvx4S729G0pS8vXBjkAoG9jA') },
    { id: 'irshad-40', name: 'ኢርሻድ ደርስ 40.mp3', type: 'audio', url: getDirectLink('1_S8fzKf_Rt09DZ8wR6Rp1oAoRQGFYJcn') },
    { id: 'irshad-41', name: 'ኢርሻድ ደርስ 41.mp3', type: 'audio', url: getDirectLink('1Tp4ImBJmZm8Ahjj_NdJ1G7DcbgxXCToX') },
    { id: 'irshad-42', name: 'ኢርሻድ ደርስ 42.mp3', type: 'audio', url: getDirectLink('1cN6s4Ofbqba4DpaxFH5XUppO0iOrZDr8') },
    { id: 'irshad-43', name: 'ኢርሻድ ደርስ 43.mp3', type: 'audio', url: getDirectLink('1KRuCf6VCTozqXucyMS2euCYJu6ts1x8W') },
    { id: 'irshad-44', name: 'ኢርሻድ ደርስ 44.mp3', type: 'audio', url: getDirectLink('1KRuCf6VCTozqXucyMS2euCYJu6ts1x8W') },
    { id: 'irshad-45', name: 'ኢርሻድ ደርስ 45.mp3', type: 'audio', url: getDirectLink('1Sne0IzygxymKRcGx9rt26ut_euu8Sna4') },
    { id: 'irshad-46', name: 'ኢርሻድ ደርስ 46.mp3', type: 'audio', url: getDirectLink('1y5P9z5ihU0-KRFCgBOyZRdf0TmfmBEp7') },
    { id: 'irshad-47', name: 'ኢርሻድ ደርስ 47.mp3', type: 'audio', url: getDirectLink('1c6vtrhi6pE1n63QKSbc8QWiNnEZzYHbJ') },
    { id: 'irshad-48', name: 'ኢርሻድ ደርስ 48.mp3', type: 'audio', url: getDirectLink('1GmSdHDlz2028oLGLsLCP7VacNbTcvgEZ') },
    { id: 'irshad-49', name: 'ኢርሻድ ደርስ 49.mp3', type: 'audio', url: getDirectLink('1ciQQ4AKUjFiE16kN_05vntWECQC-_sY-') },
    { id: 'irshad-50', name: 'ኢርሻድ ደርስ 50.mp3', type: 'audio', url: getDirectLink('1z25cPojkvCZoybe80v-bFbfNADpQB1RM') },
    { id: 'irshad-51', name: 'ኢርሻድ ደርስ 51.mp3', type: 'audio', url: getDirectLink('1b4SyFy3UB55x0EbEKg770giZYL5Rt9NF') },
    { id: 'irshad-52', name: 'ኢርሻድ ደርስ 52.mp3', type: 'audio', url: getDirectLink('1AdPWtc4j8q2nT42VqMXbjLAb1nrwx7Bk') },
    { id: 'irshad-53', name: 'ኢርሻድ ደርስ 53.mp3', type: 'audio', url: getDirectLink('1GQpNhkkwu7ESpWcYsiaFMfWth_fAM1o8') },
    { id: 'irshad-54', name: 'ኢርሻድ ደርስ 54.mp3', type: 'audio', url: getDirectLink('1fdVmFUwy3Zm-bF7TGHk4y61p0pbXHJv1') },
    { id: 'irshad-55', name: 'ኢርሻድ ደርስ 55.mp3', type: 'audio', url: getDirectLink('122TqXlxYb4g0nNJOcq_xCp6NTiuop8_F') },
    { id: 'irshad-56', name: 'ኢርሻድ ደርስ 56.mp3', type: 'audio', url: getDirectLink('1QSYgsT5FvmqL1-GPp_0jeRdzGepfLZ5v') },
    { id: 'irshad-57', name: 'ኢርሻድ ደርስ 57.mp3', type: 'audio', url: getDirectLink('1L44kqaZrHUPf6Dxci4wUO9JcISGi_FEx') },
    { id: 'irshad-58', name: 'ኢርሻድ ደርስ 58.mp3', type: 'audio', url: getDirectLink('12VaQZDMKrtQVtlSiPKfsvE3lOvqAyEGA') },
    { id: 'irshad-59', name: 'ኢርሻድ ደርስ 59.mp3', type: 'audio', url: getDirectLink('1zxoNoauVZ_6z4L7xETpL96OwWw9vniJJ') },
    { id: 'irshad-60', name: 'ኢርሻድ ደርስ 60.mp3', type: 'audio', url: getDirectLink('18HEUN62VHeT5lWgPj8iXLcS0QkGmp6tr') },
    { id: 'irshad-61', name: 'ኢርሻድ ደርስ 61.mp3', type: 'audio', url: getDirectLink('1aWtAc1honx6xMqaLmCLQxsIQQvDm7oaw') },
    { id: 'irshad-62', name: 'ኢርሻድ ደርስ 62.mp3', type: 'audio', url: getDirectLink('1iUWoLO0y6cuOwJPpS2-bQ5-rsShWgXpO') },
    { id: 'irshad-63', name: 'ኢርሻድ ደርስ 63.mp3', type: 'audio', url: getDirectLink('1_FNrwa4kt_giWqRlMnfHBYhENifX3Os0') },
    { id: 'irshad-64', name: 'ኢርሻድ ደርስ 64.mp3', type: 'audio', url: getDirectLink('1TONRNvMsYCpz5yaoRs2JcVAjo9i2E3jW') },
    { id: 'irshad-65', name: 'ኢርሻድ ደርስ 65.mp3', type: 'audio', url: getDirectLink('1Z8jdCm8_9HFWYx8ovR_ZP5r7VzdxUh1R') },
    { id: 'irshad-66', name: 'ኢርሻድ ደርስ 66.mp3', type: 'audio', url: getDirectLink('1sszKHeDWb1V5Dod6dqZb4aoUy0nmsM_O') },
    { id: 'irshad-67', name: 'ኢርሻድ ደርስ 67.mp3', type: 'audio', url: getDirectLink('1EYYpvX_WvGp1q5jmAsIfPK29BarIiJyU') },
    { id: 'irshad-68', name: 'ኢርሻድ ደርስ 68.mp3', type: 'audio', url: getDirectLink('10XiWGAobgiA9wU7ASH5e_HANdNLrfecE') },
    { id: 'irshad-69', name: 'ኢርሻድ ደርስ 69.mp3', type: 'audio', url: getDirectLink('1c5ATTPYKoEbYYd7EeomFWyb34S954VU7') },
    { id: 'irshad-70', name: 'ኢርሻድ ደርስ 70.mp3', type: 'audio', url: getDirectLink('1y-pHSkeO0jB4scKUv5aulpw7DsP39wYq') },
    { id: 'irshad-71', name: 'ኢርሻድ ደርስ 71.mp3', type: 'audio', url: getDirectLink('1FIzH2PiwIzoLGXmTNhm1Skn9by9NdPdu') },
    { id: 'irshad-72', name: 'ኢርሻድ ደርስ 72.mp3', type: 'audio', url: getDirectLink('1AzhK-Upw990aBuY0GasMHig8B-o3E3Tt') },
    { id: 'irshad-73', name: 'ኢርሻድ ደርስ 73.mp3', type: 'audio', url: getDirectLink('1yfj-_IZj-PVxI7pHIssOpiKxoYZ4FeMC') },
    { id: 'irshad-74', name: 'ኢርሻድ ደርስ 74.mp3', type: 'audio', url: getDirectLink('1G_HgDQonb8tjD_FKmDt-bmMrT7XrCoJA') },
    { id: 'irshad-75', name: 'ኢርሻድ ደርስ 75.mp3', type: 'audio', url: getDirectLink('1a4S7bT6dTeU7ouCOfSZA5lYcPrKSBRam') },
    { id: 'irshad-76', name: 'ኢርሻድ ደርስ 76.mp3', type: 'audio', url: getDirectLink('17Sphh5yumB6g1iM-JvHgNTpX89M2H6vk') },
    { id: 'irshad-77', name: 'ኢርሻድ ደርስ 77.mp3', type: 'audio', url: getDirectLink('1Xh9VF1jufcB70FYqUqEgsDe2x-73eV_C') },
    { id: 'irshad-78', name: 'ኢርሻድ ደርስ 78.mp3', type: 'audio', url: getDirectLink('1alTD8i9sK5EO1aWLSrKPKlyjpjSElrd_') },
    { id: 'irshad-79', name: 'ኢርሻድ ደርስ 79.mp3', type: 'audio', url: getDirectLink('18YI6V7j9Cl1oNOOPWu5BhTW_aolGliy4') },
    { id: 'irshad-80', name: 'ኢርሻድ ደርስ 80.mp3', type: 'audio', url: getDirectLink('1rSW_2YGE4znic9W7DqxfmgD0rmcRa7DS') },
    { id: 'irshad-81', name: 'ኢርሻድ ደርስ 81.mp3', type: 'audio', url: getDirectLink('1CIPo5tt77SiBTTuQqvkQbeSbGsN3Fskv') },
    { id: 'irshad-82', name: 'ኢርሻድ ደርስ 82.mp3', type: 'audio', url: getDirectLink('1A0Es31M791ReB7eFZkb27v936DxD4VVE') },
    { id: 'irshad-83', name: 'ኢርሻድ ደርስ 83.mp3', type: 'audio', url: getDirectLink('1rqIwdyZMXYF8rTgnFYBok76gkXA649b7') },
    { id: 'irshad-84', name: 'ኢርሻድ ደርስ 84.mp3', type: 'audio', url: getDirectLink('1XdlLfPUsyn1FX5rJrfR6R_HnrlmwYVLm') },
    { id: 'irshad-85', name: 'ኢርሻድ ደርስ 85.mp3', type: 'audio', url: getDirectLink('1CBEZjO27hDzfgueS6xLQPVXtq-wt1U-G') },
    { id: 'irshad-86', name: 'ኢርሻድ ደርስ 86.mp3', type: 'audio', url: getDirectLink('1JVYI3SqxFPTLMmhOI1RQLeRohZJY3VAo') },
    { id: 'irshad-87', name: 'ኢርሻድ ደርስ 87.mp3', type: 'audio', url: getDirectLink('1mzRiSKjc8Ew7wwctcFNf7rz5gzn_OM3n') },
    { id: 'irshad-88', name: 'ኢርሻድ ደርስ 88.mp3', type: 'audio', url: getDirectLink('1nm9EKPbX18CUPphhcbrQovemqEbkS5kC') },
    { id: 'irshad-89', name: 'ኢርሻድ ደርስ 89.mp3', type: 'audio', url: getDirectLink('1D5e90IKDyTTbi7FGYOefhokpaMPVfCRR') },
    { id: 'irshad-90', name: 'ኢርሻድ ደርስ 90.mp3', type: 'audio', url: getDirectLink('1Nq-RwVwGsAhOtdQmjeUN8YQTrM4LS4fC') },
    { id: 'irshad-91', name: 'ኢርሻድ ደርስ 91.mp3', type: 'audio', url: getDirectLink('1t0s7suBuoWE-RY0oyONO9WtnCbQUZZ4b') },
    { id: 'irshad-92', name: 'ኢርሻድ ደርስ 92.mp3', type: 'audio', url: getDirectLink('13nIdo9xlDatSWtVDMhetosGtP6TbetAq') },
    { id: 'irshad-93', name: 'ኢርሻድ ደርስ 93.mp3', type: 'audio', url: getDirectLink('1ubG6a2GB8_ZMXki3H7dw40VTtOEmNCPA') },
    { id: 'irshad-94', name: 'ኢርሻድ ደርስ 94.mp3', type: 'audio', url: getDirectLink('1RqS3aDPrYY_ycgRHIh6HGeNi9Ik6JfKl') },
    { id: 'irshad-95', name: 'ኢርሻድ ደርስ 95.mp3', type: 'audio', url: getDirectLink('1NLpFdgqigiBhRWDJXGx4r-Q97IbdxuXJ') },
    { id: 'irshad-96', name: 'ኢርሻድ ደርስ 96.mp3', type: 'audio', url: getDirectLink('1ArBc55G_ygvKGG-1foZlpWOX7rn27HJ6') },
    { id: 'irshad-97', name: 'ኢርሻድ ደርስ 97.mp3', type: 'audio', url: getDirectLink('1JhuQq0uYnG7gCG0SidA9_ZV9R3UT4dPy') },
    { id: 'irshad-98', name: 'ኢርሻድ ደርስ 98.mp3', type: 'audio', url: getDirectLink('18rhVzLfOGOSj2ttHnGakuQANFClqDiSo') },
    { id: 'irshad-99', name: 'ኢርሻድ ደርስ 99.mp3', type: 'audio', url: getDirectLink('1k4bTBweb4y2DW_RF6NZ1nP3vjwMrxvTC') },
    { id: 'irshad-100', name: 'ኢርሻድ ደርስ 100.mp3', type: 'audio', url: getDirectLink('14f0hFnpRHs2XNAFA3qmsFZkB6-w3QzRQ') },
    { id: 'irshad-101', name: 'ኢርሻድ ደርስ 101.mp3', type: 'audio', url: getDirectLink('1CgMFgopv3RM-kVduIYBMyM1i1bXfeKsO') },
    { id: 'irshad-102', name: 'ኢርሻድ ደርስ 102.mp3', type: 'audio', url: getDirectLink('1iyYYhmMlcbAtTEWDunUBcKN484oiELIn') },
    { id: 'irshad-103', name: 'ኢርሻድ ደርስ 103.mp3', type: 'audio', url: getDirectLink('1MFMTNgfjOD1W7k_3KMQm026TeMbHvoPm') },
    { id: 'irshad-104', name: 'ኢርሻድ ደርስ 104.mp3', type: 'audio', url: getDirectLink('1c6SmoSo2dw4afK2Ck2866BcnUN_iNum7') },
    { id: 'irshad-105', name: 'ኢርሻድ ደርስ 105.mp3', type: 'audio', url: getDirectLink('1MMXxBfWTmWKbD0AVh91lbTfDK1qIZnVd') },
    { id: 'irshad-106', name: 'ኢርሻድ ደርስ 106.mp3', type: 'audio', url: getDirectLink('1EvhRObhK0uFfX2bazuVZhlKVqOi1-8GR') },
];
