import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const IRSHAD_FILES: DriveFile[] = [
    {
        id: 'irshad-pdf',
        name: 'ኢርሻድ.pdf',
        type: 'pdf',
        url: getDirectLink('1hiwXoR1pv6Yk2BGHydMD03Nh6XyaitQE'),
    },
    { id: 'irshad-1', name: 'ኢርሻድ ደርስ 1.mp3', type: 'audio', url: getDirectLink('1XP11nmT3PUl9JyoOnRtV9tO1fz_RTZSo') },
    { id: 'irshad-2', name: 'ኢርሻድ ደርስ 2.mp3', type: 'audio', url: getDirectLink('1ucezLHnPYchHD7RzAedYaFK5p9ZqTQi3') },
    { id: 'irshad-3', name: 'ኢርሻድ ደርስ 3.mp3', type: 'audio', url: getDirectLink('18PLxZVL21bZxLa-8Cxq6CmNOMIUTVr96') },
    { id: 'irshad-4', name: 'ኢርሻድ ደርስ 4.mp3', type: 'audio', url: getDirectLink('1_kWpmLMHC3eOWQIG_Gw-sYw9JgCqAcp7') },
    { id: 'irshad-5', name: 'ኢርሻድ ደርስ 5.mp3', type: 'audio', url: getDirectLink('14JSBlAluKb-0HeVdOicHBgZWrgc_MeOq') },
    { id: 'irshad-6', name: 'ኢርሻድ ደርስ 6.mp3', type: 'audio', url: getDirectLink('1u8p3y49CzsiUnr81XbWOPr8vg8Ws0Q-g') },
    { id: 'irshad-7', name: 'ኢርሻድ ደርስ 7.mp3', type: 'audio', url: getDirectLink('1Z3PPOBF9mLePkKoOT4xqP3UPtm2tuA31') },
    { id: 'irshad-8', name: 'ኢርሻድ ደርስ 8.mp3', type: 'audio', url: getDirectLink('1aPXiVmqqg81sir-Ly65pPlmkPIWdBzKC') },
    { id: 'irshad-9', name: 'ኢርሻድ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1MQ9W28K1tGk2lC8Pw9KjYra9sfClby4b') },
    { id: 'irshad-10', name: 'ኢርሻድ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1_kJ4k-tLTshn7B-unumhT2gYgwg7h7pv') },
    { id: 'irshad-11', name: 'ኢርሻድ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1o7McDYk3erJLc6K34FQic0bQGPdWZmju') },
    { id: 'irshad-12', name: 'ኢርሻድ ደርስ 12.mp3', type: 'audio', url: getDirectLink('1f_gMGBPYoXrQiOK09kP0aqWGP-nHgSus') },
    { id: 'irshad-13', name: 'ኢርሻድ ደርስ 13.mp3', type: 'audio', url: getDirectLink('19OOdrU-AY5KE_t77ygcsrP37vnbdYXSc') },
    { id: 'irshad-14', name: 'ኢርሻድ ደርስ 14.mp3', type: 'audio', url: getDirectLink('18k7uWEZLYhfLG_3hnVgIW3MGjX-gdQHV') },
    { id: 'irshad-15', name: 'ኢርሻድ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1MMgbMuO5xS6VXS5B9IpcSMd6Rgb1j66T') },
    { id: 'irshad-16', name: 'ኢርሻድ ደርስ 16.mp3', type: 'audio', url: getDirectLink('174xBvubob_DlnKV12NVP9YhGytjDG5jP') },
    { id: 'irshad-17', name: 'ኢርሻድ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1sWG3psakvbA4sCbhk42wljPhKi4KnLf5') },
    { id: 'irshad-18', name: 'ኢርሻድ ደርስ 18.mp3', type: 'audio', url: getDirectLink('1izQf4fRcYV2vrRew12PhXYYqeg96R5br') },
    { id: 'irshad-19', name: 'ኢርሻድ ደርስ 19.mp3', type: 'audio', url: getDirectLink('19HrG0eMpQFBqAVCoIC6HsG_-YJABVlPm') },
    { id: 'irshad-20', name: 'ኢርሻድ ደርስ 20.mp3', type: 'audio', url: getDirectLink('1n_-y1MGWK9x4TS5ehD66txp5Ie29wtxx') },
    { id: 'irshad-21', name: 'ኢርሻድ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1diH17Bat5O-obRTzAWCR-_SEUZ7RBz_9') },
    { id: 'irshad-22', name: 'ኢርሻድ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1PC_cMAkHZkbr08iR3gDByB2WibpUv646') },
    { id: 'irshad-23', name: 'ኢርሻድ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1dY_xo_CvUqom1VAk4m5uvvl__-vtaeBF') },
    { id: 'irshad-24', name: 'ኢርሻድ ደርስ 24.mp3', type: 'audio', url: getDirectLink('1_q8DXpGs-T4NlW-iyVxpa3yrQrR79QSj') },
    { id: 'irshad-25', name: 'ኢርሻድ ደርስ 25.mp3', type: 'audio', url: getDirectLink('15T4lzBZJ16nISTi_8EWb-hw7ap7sszzY') },
    { id: 'irshad-26', name: 'ኢርሻድ ደርስ 26.mp3', type: 'audio', url: getDirectLink('150Ca-HYrzDDKpx44oDp3VJHMiZcLcDsm') },
    { id: 'irshad-27', name: 'ኢርሻድ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1TZyPku3-g3seMCBdzEtOOBWfsfmn7UpE') },
    { id: 'irshad-28', name: 'ኢርሻድ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1c-cM4R7ix0MuQ93kLc2R2G94DSS2pdJI') },
    { id: 'irshad-29', name: 'ኢርሻድ ደርስ 29.mp3', type: 'audio', url: getDirectLink('1GOFsij7oC5W262C7BrMVTHA-gxshM1Qm') },
    { id: 'irshad-30', name: 'ኢርሻድ ደርስ 30.mp3', type: 'audio', url: getDirectLink('1j6LLoC7lH-FWK0vRINS7CDHamkbpgbdb') },
    { id: 'irshad-31', name: 'ኢርሻድ ደርስ 31.mp3', type: 'audio', url: getDirectLink('1p2rH14o6txepxlf6bWbK_YQTq8Ys-08f') },
    { id: 'irshad-32', name: 'ኢርሻድ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1GGFn9EJ7oz8e1Qgfpb_mWkGsWjYHTwou') },
    { id: 'irshad-33', name: 'ኢርሻድ ደርስ 33.mp3', type: 'audio', url: getDirectLink('1r2gM8XrQR9jfIMcTPWqPGyDOEFWZ1xE1') },
    { id: 'irshad-34', name: 'ኢርሻድ ደርስ 34.mp3', type: 'audio', url: getDirectLink('193eS2QV6f0gn-2n-Gf_n-0fZFCueEC6p') },
    { id: 'irshad-35', name: 'ኢርሻድ ደርስ 35.mp3', type: 'audio', url: getDirectLink('1j_27KC3uattt_Io7zaxlLyLNCCAkIQaH') },
    { id: 'irshad-36', name: 'ኢርሻድ ደርስ 36.mp3', type: 'audio', url: getDirectLink('1R2gQFP72jo3U8znzzw-M5kGeGOCnwDwY') },
    { id: 'irshad-37', name: 'ኢርሻድ ደርስ 37.mp3', type: 'audio', url: getDirectLink('1co9DSykjw9XVfwhHX0J-6JAJe-MyYPvV') },
    { id: 'irshad-38', name: 'ኢርሻድ ደርስ 38.mp3', type: 'audio', url: getDirectLink('1xTGGrev_8x8-YpcLdEfgq3mYh94X2qh2') },
    { id: 'irshad-39', name: 'ኢርሻድ ደርስ 39.mp3', type: 'audio', url: getDirectLink('1Auxm9adqgLSgL3fQYpcsG8yTFLEvGW8m') },
    { id: 'irshad-40', name: 'ኢርሻድ ደርስ 40.mp3', type: 'audio', url: getDirectLink('1niMyzYMUP1ia8K-q5y_o_pKFhAW09d-L') },
    { id: 'irshad-41', name: 'ኢርሻድ ደርስ 41.mp3', type: 'audio', url: getDirectLink('1dRihKRxC57jkUvi1X8JFczmmdvGm6OfL') },
    { id: 'irshad-42', name: 'ኢርሻድ ደርስ 42.mp3', type: 'audio', url: getDirectLink('1p51G7PxVEjYh7SvMpoNqjE1g-5NSWBc3') },
    { id: 'irshad-43', name: 'ኢርሻድ ደርስ 43.mp3', type: 'audio', url: getDirectLink('1f4idDhd0CSVTRsPYXgz2_E5weaWC-mPn') },
    { id: 'irshad-44', name: 'ኢርሻድ ደርስ 44.mp3', type: 'audio', url: getDirectLink('1f4idDhd0CSVTRsPYXgz2_E5weaWC-mPn') },
    { id: 'irshad-45', name: 'ኢርሻድ ደርስ 45.mp3', type: 'audio', url: getDirectLink('10Zcb8XMO28TV0t5BfBVjmCEcwL3JBO1K') },
    { id: 'irshad-46', name: 'ኢርሻድ ደርስ 46.mp3', type: 'audio', url: getDirectLink('1pVBdmaKtcCMsIFbq-kU4reseZjlP2alL') },
    { id: 'irshad-47', name: 'ኢርሻድ ደርስ 47.mp3', type: 'audio', url: getDirectLink('1cDnW7me6lNIPTupyBcMTDUCoVNq0FGeE') },
    { id: 'irshad-48', name: 'ኢርሻድ ደርስ 48.mp3', type: 'audio', url: getDirectLink('1gEDy8EF9ECyaXbvACBksrA_xxfTAhb4-') },
    { id: 'irshad-49', name: 'ኢርሻድ ደርስ 49.mp3', type: 'audio', url: getDirectLink('1ByIFMpZ6QxkeLI5z5u_ZwFBIv-4jHak-') },
    { id: 'irshad-50', name: 'ኢርሻድ ደርስ 50.mp3', type: 'audio', url: getDirectLink('1xSGCpWDAOi9jBnvIJcAgqCAaSNvXrHvm') },
    { id: 'irshad-51', name: 'ኢርሻድ ደርስ 51.mp3', type: 'audio', url: getDirectLink('1yEIRlE-XjXwI-0mb6QVA-tDvUjOf9JON') },
    { id: 'irshad-52', name: 'ኢርሻድ ደርስ 52.mp3', type: 'audio', url: getDirectLink('1ghUcqX70a9UBxEsE1RKh_7bCs1xJOCpu') },
    { id: 'irshad-53', name: 'ኢርሻድ ደርስ 53.mp3', type: 'audio', url: getDirectLink('1MYGB8DJUA3rYnBYIBH-kZsGdG4QFRM3d') },
    { id: 'irshad-54', name: 'ኢርሻድ ደርስ 54.mp3', type: 'audio', url: getDirectLink('1cHa38mbsBchDGXFJnyL43HdPZYVK_J5A') },
    { id: 'irshad-55', name: 'ኢርሻድ ደርስ 55.mp3', type: 'audio', url: getDirectLink('1jUGV47DmtuQb2BoUNIziaAf_ie47G8DT') },
    { id: 'irshad-56', name: 'ኢርሻድ ደርስ 56.mp3', type: 'audio', url: getDirectLink('1jkF4a9jrAYf_ShZYvdjB8pICcC3XfZ5U') },
    { id: 'irshad-57', name: 'ኢርሻድ ደርስ 57.mp3', type: 'audio', url: getDirectLink('1KB-gsIIWtqbSYaj8poeuaqDGLeT0Vh0t') },
    { id: 'irshad-58', name: 'ኢርሻድ ደርስ 58.mp3', type: 'audio', url: getDirectLink('1g5e4tG-QzhcvZNJO27TR5--AXz5Q2a4X') },
    { id: 'irshad-59', name: 'ኢርሻድ ደርስ 59.mp3', type: 'audio', url: getDirectLink('1CnFtOBosK2pCxLDoMXryNjLWNgGtLVD5') },
    { id: 'irshad-60', name: 'ኢርሻድ ደርስ 60.mp3', type: 'audio', url: getDirectLink('1SVgt6dosfhwb5oMPwb6xGgC6XZnB3YX9') },
    { id: 'irshad-61', name: 'ኢርሻድ ደርስ 61.mp3', type: 'audio', url: getDirectLink('16numWWDgnQbX_fE2yPh2Y4zwlyfqvc8n') },
    { id: 'irshad-62', name: 'ኢርሻድ ደርስ 62.mp3', type: 'audio', url: getDirectLink('1zX6QSnKfihOW3sIEe1dXXSN3Ech5m8pp') },
    { id: 'irshad-63', name: 'ኢርሻድ ደርስ 63.mp3', type: 'audio', url: getDirectLink('1pVgSR-o-RHujHWcjWMDZbN5iJMH43Kcq') },
    { id: 'irshad-64', name: 'ኢርሻድ ደርስ 64.mp3', type: 'audio', url: getDirectLink('1BAIAPgUKvYvlD4BJo7Xkvc2wkA6B284R') },
    { id: 'irshad-65', name: 'ኢርሻድ ደርስ 65.mp3', type: 'audio', url: getDirectLink('1f9GLlHgB0iBDqmdBGQ5kDXc0sSXqWmT5') },
    { id: 'irshad-66', name: 'ኢርሻድ ደርስ 66.mp3', type: 'audio', url: getDirectLink('1QfcRe2vEeOVbjOOAgOdvNK1yXdwG8qHG') },
    { id: 'irshad-67', name: 'ኢርሻድ ደርስ 67.mp3', type: 'audio', url: getDirectLink('1vodClagQxOFC160gDAEKRuu4oQ9ayagv') },
    { id: 'irshad-68', name: 'ኢርሻድ ደርስ 68.mp3', type: 'audio', url: getDirectLink('1iSAi13tSPRqLJm7mF7bUdSrr2oY6xn4y') },
    { id: 'irshad-69', name: 'ኢርሻድ ደርስ 69.mp3', type: 'audio', url: getDirectLink('14E7DYS79EUQ860YDVKPA5teYw7XE-idL') },
    { id: 'irshad-70', name: 'ኢርሻድ ደርስ 70.mp3', type: 'audio', url: getDirectLink('1l6pS1-P3zn53CAMst8OUfbN3iF-3AudY') },
    { id: 'irshad-71', name: 'ኢርሻድ ደርስ 71.mp3', type: 'audio', url: getDirectLink('1TxFowzZt7TM8Jl_Y4TYj9yNOTEw2SgMR') },
    { id: 'irshad-72', name: 'ኢርሻድ ደርስ 72.mp3', type: 'audio', url: getDirectLink('1a7tcdH9v7SrVALYpXNAR_I6gtT0VAM5G') },
    { id: 'irshad-73', name: 'ኢርሻድ ደርስ 73.mp3', type: 'audio', url: getDirectLink('1diRuO8aIx90iCbJ3zAOVE0738IKJXb3j') },
    { id: 'irshad-74', name: 'ኢርሻድ ደርስ 74.mp3', type: 'audio', url: getDirectLink('1OQdvT-SV-K8qF6CYwZTW04gpgLb_ATeO') },
    { id: 'irshad-75', name: 'ኢርሻድ ደርስ 75.mp3', type: 'audio', url: getDirectLink('1fpOU-2QyLbVndJ6PezwQAZ_WHd13JZAR') },
    { id: 'irshad-76', name: 'ኢርሻድ ደርስ 76.mp3', type: 'audio', url: getDirectLink('1Z91-btX13ArpHH0VmGukOE1EZ5goZW-l') },
    { id: 'irshad-77', name: 'ኢርሻድ ደርስ 77.mp3', type: 'audio', url: getDirectLink('1kiuqo0PPvFgQFpMKVEmvD20HUF-Dm9rZ') },
    { id: 'irshad-78', name: 'ኢርሻድ ደርስ 78.mp3', type: 'audio', url: getDirectLink('1t7GB-FE4kRv5emCiMMZF-WMAOdLct8c3') },
    { id: 'irshad-79', name: 'ኢርሻድ ደርስ 79.mp3', type: 'audio', url: getDirectLink('1V2IcY_6b-Qd1aDPECBruGQC7C8VL7pZl') },
    { id: 'irshad-80', name: 'ኢርሻድ ደርስ 80.mp3', type: 'audio', url: getDirectLink('1eILASz9W6EIbR5HZN9vta36w7uaHYFJB') },
    { id: 'irshad-81', name: 'ኢርሻድ ደርስ 81.mp3', type: 'audio', url: getDirectLink('1yHcv7fxHL5pm--kyPaaTVe0a5tL14MP2') },
    { id: 'irshad-82', name: 'ኢርሻድ ደርስ 82.mp3', type: 'audio', url: getDirectLink('1wxwIADTJuqL8jwM7ZcH25hCLYNiWKr0X') },
    { id: 'irshad-83', name: 'ኢርሻድ ደርስ 83.mp3', type: 'audio', url: getDirectLink('15EdYBHmjpJh64iScKuGERdCPcJor2sLl') },
    { id: 'irshad-84', name: 'ኢርሻድ ደርስ 84.mp3', type: 'audio', url: getDirectLink('1xk0CN8PzxJZ-c1rrqwJ5EaLv4bShb10q') },
    { id: 'irshad-85', name: 'ኢርሻድ ደርስ 85.mp3', type: 'audio', url: getDirectLink('1OnS6XCPDxZxSRKCGU_r7pzvJy8wnP-Fe') },
    { id: 'irshad-86', name: 'ኢርሻድ ደርስ 86.mp3', type: 'audio', url: getDirectLink('1mQqNvmFX8dfTl-cJ6BlImVHCvgvcnt7j') },
    { id: 'irshad-87', name: 'ኢርሻድ ደርስ 87.mp3', type: 'audio', url: getDirectLink('1y67gA25JGOAJ5Fr9_GHqbriF18boNhjR') },
    { id: 'irshad-88', name: 'ኢርሻድ ደርስ 88.mp3', type: 'audio', url: getDirectLink('1A79CGM7vTPUdfE0JCHcdGfu8PG1Jp39B') },
    { id: 'irshad-89', name: 'ኢርሻድ ደርስ 89.mp3', type: 'audio', url: getDirectLink('1s_4QYdnwnK2aD3ac9-EKb3zQ2bNgAgwc') },
    { id: 'irshad-90', name: 'ኢርሻድ ደርስ 90.mp3', type: 'audio', url: getDirectLink('1nKciBZPYgeHo9HkYjPJUoIxLAk62rikB') },
    { id: 'irshad-91', name: 'ኢርሻድ ደርስ 91.mp3', type: 'audio', url: getDirectLink('1FlSvC8xVDqx0sLmAzKkBM7MPqvBQp5M6') },
    { id: 'irshad-92', name: 'ኢርሻድ ደርስ 92.mp3', type: 'audio', url: getDirectLink('1MHLH-UOS4S-JRaoNanLZ7qQhQfxBTBwa') },
    { id: 'irshad-93', name: 'ኢርሻድ ደርስ 93.mp3', type: 'audio', url: getDirectLink('1Yu8REwLZ2A--0gF_-lw4bfSDrDocCfcc') },
    { id: 'irshad-94', name: 'ኢርሻድ ደርስ 94.mp3', type: 'audio', url: getDirectLink('1mKopZkhY2ugIxvWxyF1NQGCLqY_8zTB7') },
    { id: 'irshad-95', name: 'ኢርሻድ ደርስ 95.mp3', type: 'audio', url: getDirectLink('10obswq68cAFSKnAhX5VjpOoJ_Tw1l-X4') },
    { id: 'irshad-96', name: 'ኢርሻድ ደርስ 96.mp3', type: 'audio', url: getDirectLink('1xgfdoSvhq5iKwChE0bET0GZih1bi2oJJ') },
    { id: 'irshad-97', name: 'ኢርሻድ ደርስ 97.mp3', type: 'audio', url: getDirectLink('1PwVkIqBHqhzVPkYqGJOajuhJMunDXeEA') },
    { id: 'irshad-98', name: 'ኢርሻድ ደርስ 98.mp3', type: 'audio', url: getDirectLink('1Fh9XkJXWhrFW1DptqrmbBEaWUlOQAbuq') },
    { id: 'irshad-99', name: 'ኢርሻድ ደርስ 99.mp3', type: 'audio', url: getDirectLink('1-n7n4Fy5c2tpB1b4VyAJEnDrvD90oKmv') },
    { id: 'irshad-100', name: 'ኢርሻድ ደርስ 100.mp3', type: 'audio', url: getDirectLink('1LzKzgW7Awlco4vFjdpQvzofHJLQlCs36') },
    { id: 'irshad-101', name: 'ኢርሻድ ደርስ 101.mp3', type: 'audio', url: getDirectLink('1jD3hkdQqUizY1DGr2THDzQZrQ1Xa0ssE') },
    { id: 'irshad-102', name: 'ኢርሻድ ደርስ 102.mp3', type: 'audio', url: getDirectLink('1sygEFiJXmYUv5R_CNFijevulshtMo-cW') },
    { id: 'irshad-103', name: 'ኢርሻድ ደርስ 103.mp3', type: 'audio', url: getDirectLink('17VU-k5AXtsUBSm92USIaHHYh2vGCxvGa') },
    { id: 'irshad-104', name: 'ኢርሻድ ደርስ 104.mp3', type: 'audio', url: getDirectLink('1sS7tn_YOmxIAPWVHA1gkTdIN10unuSQC') },
    { id: 'irshad-105', name: 'ኢርሻድ ደርስ 105.mp3', type: 'audio', url: getDirectLink('1aRWX8e-QlYjbfKle9W8OGFO5dc_4PZGh') },
    { id: 'irshad-106', name: 'ኢርሻድ ደርስ 106.mp3', type: 'audio', url: getDirectLink('1rqqTq-iBb2bLaVpzJ_iURULzS0eiVrVT') },
];
