import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const KASHFU_SHUBHA_FILES: DriveFile[] = [
    {
        id: 'kashfu-shubha-pdf',
        name: 'ሸርህ ከሽፉ ሹብሀ ሊሸህ አል-ፈውዛን.pdf',
        type: 'pdf',
        url: getDirectLink('1fJmf3yci9_z50QctmD6y9P8VhbxZxgZf'),
    },
    { id: 'kashfu-shubha-1', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 1.mp3', type: 'audio', url: getDirectLink('1UkYWVgDW0uZWJP-G0fJUIWtZKffPv3b1') },
    { id: 'kashfu-shubha-2', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 2.mp3', type: 'audio', url: getDirectLink('1sbcowBvsuwCjlLkojpxImXa5vXk-r7MU') },
    { id: 'kashfu-shubha-3', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 3.mp3', type: 'audio', url: getDirectLink('1vhDgFUM94xnmS8lYd4PAB2XJSGiqdjQ1') },
    { id: 'kashfu-shubha-4', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 4.mp3', type: 'audio', url: getDirectLink('1VN_c66WV_CK-EKEJb0xVkHrt36ElqDO6') },
    { id: 'kashfu-shubha-5', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 5.mp3', type: 'audio', url: getDirectLink('1oZPOwUbhGAujJvqVjAchIdtnkyED4qJZ') },
    { id: 'kashfu-shubha-6', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 6.mp3', type: 'audio', url: getDirectLink('1FfYN3FYMCYM16Yzg2LAze8GnmOMGWi-N') },
    { id: 'kashfu-shubha-7', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 7.mp3', type: 'audio', url: getDirectLink('198ASPwYijqd0tqt6xeOg192UIPPumoHd') },
    { id: 'kashfu-shubha-8', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 8.mp3', type: 'audio', url: getDirectLink('12Z39rJneBFijC8DpIgoAsHFLanG_erX7') },
    { id: 'kashfu-shubha-9', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1j8NMeAZPj59cftVAdIzoY_zrxVbKDidd') },
    { id: 'kashfu-shubha-10', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1KFen0jQny6V9VlKL8EA0eGpVjZqJAjTy') },
    { id: 'kashfu-shubha-11', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1Jy5hKhp-ik-aIwDSJYw0cPh85fAfmOl3') },
    { id: 'kashfu-shubha-12', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 12.mp3', type: 'audio', url: getDirectLink('176n8ewGkR2BrQ4tjqsw2ohAqe-S0fXq8') },
    { id: 'kashfu-shubha-13', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 13.mp3', type: 'audio', url: getDirectLink('1r97vU0saWysX2c69ecQv9lwIN4DSF0uI') },
    { id: 'kashfu-shubha-14', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 14.mp3', type: 'audio', url: getDirectLink('1RNqOm_9GlwMWgTNDAXG4YIr_89G6yC73') },
    { id: 'kashfu-shubha-15', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1v6CpXFUaN8kol-0VmCVbLwNiz5keMuCm') },
    { id: 'kashfu-shubha-16', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 16.mp3', type: 'audio', url: getDirectLink('1EMlEEbdevNThxiowzxyXlalcAwJq69bH') },
    { id: 'kashfu-shubha-17', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1HTv7rqXEtZ609KliKVmIAmwKLZ3ybhga') },
    { id: 'kashfu-shubha-18', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 18.mp3', type: 'audio', url: getDirectLink('1b6w8_Ys2Wh96I68TgD0RXPYR8t9gDXGD') },
    { id: 'kashfu-shubha-19', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 19.mp3', type: 'audio', url: getDirectLink('1zWkLUYD-QqheBJgI6dDFTu7zfYa_GVcc') },
    { id: 'kashfu-shubha-20', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 20.mp3', type: 'audio', url: getDirectLink('1DPP6urj0b4HR3H6jAF1F8hGrQrwivTyB') },
    { id: 'kashfu-shubha-21', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1XCEA4I1qTn6vjCQUQTymcQmMiSibz4Fr') },
    { id: 'kashfu-shubha-22', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1PEje2sK6eq2dTQ0DkfNtMNxLiSVZBAYl') },
    { id: 'kashfu-shubha-23', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1bNKWirX_ch-cfmWJ0PGO2BnkzkXVvxKp') },
    { id: 'kashfu-shubha-24', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 24.mp3', type: 'audio', url: getDirectLink('1iln3aavGbdI7nY_ToGDmNlJxw2GRyJ58') },
    { id: 'kashfu-shubha-25', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 25.mp3', type: 'audio', url: getDirectLink('12PP6AghNvR6YqjKrTFoPbXepeNTGR3Iw') },
    { id: 'kashfu-shubha-26', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 26.mp3', type: 'audio', url: getDirectLink('191ba_eHd465hy5IkHlFfn7xOu1_7ZSqN') },
    { id: 'kashfu-shubha-27', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1sdxelf344Oh1nbgryqZdjNL3bMmNeMsV') },
    { id: 'kashfu-shubha-28', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1N8_7u4K1vrSamqLiXMcxcHx0hJgbACLZ') },
    { id: 'kashfu-shubha-29', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 29.mp3', type: 'audio', url: getDirectLink('191b6POWRxGFhgdfzqKznrbGQMQ2dCxKk') },
    { id: 'kashfu-shubha-30', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 30.mp3', type: 'audio', url: getDirectLink('1lHycU58nbgLggjiSqD4WMlMt2YvqXaKQ') },
    { id: 'kashfu-shubha-31', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 31.mp3', type: 'audio', url: getDirectLink('1Noh1nC1rGFJnTFPIFqroRMK4xtdWSsgd') },
    { id: 'kashfu-shubha-32', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1ztvD9EuRkCYKGE5lirJwTj0Fquez-G3K') },
    { id: 'kashfu-shubha-33', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 33.mp3', type: 'audio', url: getDirectLink('1PKpL4gRowFociZUNgvwHG95XqatnSeu3') },
    { id: 'kashfu-shubha-34', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 34.mp3', type: 'audio', url: getDirectLink('1qwEeOsrhOsQfvwA9iqC_3KZAhpU4IBNV') },
    { id: 'kashfu-shubha-35', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 35.mp3', type: 'audio', url: getDirectLink('1R14EdMqTzzlopJ1Eh5bRVN1Qu3brbuHn') },
    { id: 'kashfu-shubha-36', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 36.mp3', type: 'audio', url: getDirectLink('1j0RcR_j3BYxBLJP8xxR-NNfXGyZ0D-2_') },
    { id: 'kashfu-shubha-37', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 37.mp3', type: 'audio', url: getDirectLink('1q_HB6yuDABP6ilskASQh-gFTGNh6atOw') },
    { id: 'kashfu-shubha-38', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 38.mp3', type: 'audio', url: getDirectLink('1EeENWGX-5QMhPkXlN_13-LORo22rWKy9') },
    { id: 'kashfu-shubha-39', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 39.mp3', type: 'audio', url: getDirectLink('1kxLdVekRhzoskgwJN0d8uwygFjtZvaKf') },
    { id: 'kashfu-shubha-40', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 40.mp3', type: 'audio', url: getDirectLink('1EoS_muXfUSjkKenFmeIljhZzNa3m6_3K') },
    { id: 'kashfu-shubha-41', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 41.mp3', type: 'audio', url: getDirectLink('1kKcke17lSfYYdXQqYkKwIOw22RYIqUl6') },
    { id: 'kashfu-shubha-42', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 42.mp3', type: 'audio', url: getDirectLink('133ry8J2nCnT5EV9N_RlDvF5ehd328cHc') },
    { id: 'kashfu-shubha-43', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 43.mp3', type: 'audio', url: getDirectLink('1rWVpTNksBJxgCXpzAdC0pA12DMbCIjux') },
    { id: 'kashfu-shubha-44', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 44.mp3', type: 'audio', url: getDirectLink('1K54IkHSiFvZFUk_4x0S7pN0ImiAwSbRa') },
    { id: 'kashfu-shubha-45', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 45.mp3', type: 'audio', url: getDirectLink('12esZgHgh5Prv823UUAJQ5crppPmkDEaW') },
    { id: 'kashfu-shubha-46', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 46.mp3', type: 'audio', url: getDirectLink('1QKITPvMXnlzA9D17X_8AmKy8zU9wevq9') },
    { id: 'kashfu-shubha-47', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 47.mp3', type: 'audio', url: getDirectLink('1nzfyq1I9Y-dFUUG8nDQw3jw0QuaeNa8J') },
    { id: 'kashfu-shubha-48', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 48.mp3', type: 'audio', url: getDirectLink('1PQ9Xvz3ANZ_cH_B_1jD5BgCJz8V0t8nW') },
    { id: 'kashfu-shubha-49', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 49.mp3', type: 'audio', url: getDirectLink('1Kynkhqs2wjjPIvXxZoowXbMQds3aAS6U') },
    { id: 'kashfu-shubha-50', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 50.mp3', type: 'audio', url: getDirectLink('1WucN9jloVRsKudmMltuB1zrIXsKH21r4') },
    { id: 'kashfu-shubha-51', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 51.mp3', type: 'audio', url: getDirectLink('1MYeBl17o4vbocG0o6rOrYaUHpSgTwhN9') },
    { id: 'kashfu-shubha-52', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 52.mp3', type: 'audio', url: getDirectLink('1rU12M-xOdUboKaT_vCGFXDnVtzgMIpp4') },
    { id: 'kashfu-shubha-53', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 53.mp3', type: 'audio', url: getDirectLink('1kriN4B6169rHJcd9lP1-VmanUPlKy48Q') },
    { id: 'kashfu-shubha-54', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 54.mp3', type: 'audio', url: getDirectLink('1lp22xbRE7KV5gn_BYDA7V7xxye-GW_fe') },
    { id: 'kashfu-shubha-55', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 55.mp3', type: 'audio', url: getDirectLink('17OVEkxPrm0iiQ17EhaXmSVyIUEf5bxl5') },
    { id: 'kashfu-shubha-56', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 56.mp3', type: 'audio', url: getDirectLink('1FrCO7JRhj4SlYvtR5S6pmvAL_z4Hanpt') },
    { id: 'kashfu-shubha-57', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 57.mp3', type: 'audio', url: getDirectLink('1ivg5I2BBffLgm8_cE8y_wSnshVBmEy4E') },
    { id: 'kashfu-shubha-58', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 58.mp3', type: 'audio', url: getDirectLink('1B4yX0ZPzQaiGzohyFSpplTQh8QyWsPYF') },
    { id: 'kashfu-shubha-59', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 59.mp3', type: 'audio', url: getDirectLink('19d_ZrJo9S723A-haH-_pEUMSR-jwWanl') },
    { id: 'kashfu-shubha-60', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 60.mp3', type: 'audio', url: getDirectLink('1KcO5D8jAI54jFV26eaB76f0Nd2nhUMND') },
    { id: 'kashfu-shubha-61', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 61.mp3', type: 'audio', url: getDirectLink('1WBu2tpArz9khQ_Jp5KC0hvkRojQcY7sY') },
    { id: 'kashfu-shubha-62', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 62.mp3', type: 'audio', url: getDirectLink('1yvVc4upPqFlzaXTPKCpKLQ-z9cu-gc64') },
    { id: 'kashfu-shubha-63', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 63.mp3', type: 'audio', url: getDirectLink('1cYmnylCWsOlcBr2slX0XBnkv5JX0nb_3') },
    { id: 'kashfu-shubha-64', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 64.mp3', type: 'audio', url: getDirectLink('1qaIk8TX7zMcnLBoATMdC-BUArxc6GDdw') },
    { id: 'kashfu-shubha-65', name: 'ሸርህ ከሽፉ ሹብሀ ደርስ 65.mp3', type: 'audio', url: getDirectLink('1C-gc6EPiC98VEKWPb6RVCDkU66dzlOo1') },
];
