import { Category, DriveFile } from '../types';

// Helper to get direct download links from Google Drive
const getDirectLink = (id: string) => `https://docs.google.com/uc?export=download&id=${id}&confirm=t`;

const MUMTIC_FILES: DriveFile[] = [
    {
        id: '1',
        name: 'ሙምቲዕ.pdf',
        type: 'pdf',
        url: getDirectLink('1bXCa2qS_Lq8NpCA1NDFArMU79D2kM1Pi'),
    },
    {
        id: '137',
        name: 'ሙምቲዕ ደርስ 137.mp3',
        type: 'audio',
        url: getDirectLink('1yl7g5X85VqjUhSKBdKhdAsBXLgHMcruD'),
    },
    {
        id: '138',
        name: 'ሙምቲዕ ደርስ 138.mp3',
        type: 'audio',
        url: getDirectLink('1wDFBHYdZCwSP1aRgnFAcw849Iaxv2Teq'),
    },
    {
        id: '139',
        name: 'ሙምቲዕ ደርስ 139.mp3',
        type: 'audio',
        url: getDirectLink('1ZmkGHM_3aCsitKFe30_SA50Qye0rvnJ9'),
    },
    {
        id: '140',
        name: 'ሙምቲዕ ደርስ 140.mp3',
        type: 'audio',
        url: getDirectLink('1f_nDKEzMv2pRa_SYEzVvVJnyDYXQh6V9'),
    },
    {
        id: '141',
        name: 'ሙምቲዕ ደርስ 141.mp3',
        type: 'audio',
        url: getDirectLink('1ia7bSMf7cy6HRRx8Tv1rKPCka5m2oxj2'),
    },
    {
        id: '142',
        name: 'ሙምቲዕ ደርስ 142.mp3',
        type: 'audio',
        url: getDirectLink('1pnHI5iHvaE4_c34IZEtoGOtpUO9udF9R'),
    },
    {
        id: '143',
        name: 'ሙምቲዕ ደርስ 143.mp3',
        type: 'audio',
        url: getDirectLink('1GsQbGdfeGwXUG7TgIpuClJQUTrrCCGPJ'),
    },
    {
        id: '144',
        name: 'ሙምቲዕ ደርስ 144.mp3',
        type: 'audio',
        url: getDirectLink('1KqaGmjpNHCGYF3VykOGrXoN_12X6bl5I'),
    },
    {
        id: '145',
        name: 'ሙምቲዕ ደርስ 145.mp3',
        type: 'audio',
        url: getDirectLink('10rfXnMIENaAzn2tkuNl-j7VXcyoKJQb6'),
    },
    {
        id: '146',
        name: 'ሙምቲዕ ደርስ 146.mp3',
        type: 'audio',
        url: getDirectLink('1Rts0M1_otBVqF_unQHqbI6vQKfyIdYH-'),
    },
    {
        id: '147',
        name: 'ሙምቲዕ ደርስ 147.mp3',
        type: 'audio',
        url: getDirectLink('14LK9fhkSvWsY8zBs0XSBAhM6-lzgIThZ'),
    },
    {
        id: '148',
        name: 'ሙምቲዕ ደርስ 148.mp3',
        type: 'audio',
        url: getDirectLink('1XcnkJyDb3PhtOGxnArA6xVPTwm3IboW7'),
    },
    {
        id: '149',
        name: 'ሙምቲዕ ደርስ 149.mp3',
        type: 'audio',
        url: getDirectLink('1OUK3GflSDjVOtDGNnHu7L3svfsTF_kgz'),
    },
    {
        id: '150',
        name: 'ሙምቲዕ ደርስ 150.mp3',
        type: 'audio',
        url: getDirectLink('1I-LFIGx1TnWGwvkj-eKe6soAfIrb76KN'),
    },
    {
        id: '151',
        name: 'ሙምቲዕ ደርስ 151.mp3',
        type: 'audio',
        url: getDirectLink('1Xf-MvSmekWIa-nqzGAvc-K_QcyNhm5-3'),
    },
    {
        id: '152',
        name: 'ሙምቲዕ ደርስ 152.mp3',
        type: 'audio',
        url: getDirectLink('1F_Sgs8ciCTAjCIw-ktvTliZs0zrnh_v7'),
    },
    {
        id: '153',
        name: 'ሙምቲዕ ደርስ 153.mp3',
        type: 'audio',
        url: getDirectLink('11oRBOPLhEYOAv-RJJUrvAXLrn4hX3bPR'),
    },
    {
        id: '154',
        name: 'ሙምቲዕ ደርስ 154.mp3',
        type: 'audio',
        url: getDirectLink('1NnLDAw5U4fVk86I-Bv02WAlV0nDvM-UC'),
    },
    {
        id: '155',
        name: 'ሙምቲዕ ደርስ 155.mp3',
        type: 'audio',
        url: getDirectLink('1Qr9Vzy230yeq4NguTMoy0k3CJ76BFwPh'),
    },
    {
        id: '156',
        name: 'ሙምቲዕ ደርስ 156.mp3',
        type: 'audio',
        url: getDirectLink('1xkDRQoLWUMdMauk2rOkSAAR87BhVZxOO'),
    },
    {
        id: '157',
        name: 'ሙምቲዕ ደርስ 157.mp3',
        type: 'audio',
        url: getDirectLink('1o3s5FmJP2Vgcvvm7InAYFZ8EYCKjPJ8D'),
    },
    {
        id: '158',
        name: 'ሙምቲዕ ደርስ 158.mp3',
        type: 'audio',
        url: getDirectLink('1dss57EIHaec9rm3GfwpwOnwuEV5JVucz'),
    },
    {
        id: '159',
        name: 'ሙምቲዕ ደርስ 159.mp3',
        type: 'audio',
        url: getDirectLink('1MRa59EsB3gaoks-JSTF6SAEs5KlznsKh'),
    },
    {
        id: '160',
        name: 'ሙምቲዕ ደርስ 160.mp3',
        type: 'audio',
        url: getDirectLink('1Y1XLGKyfGX21hGnBzCuCU2aGDCJwPeiD'),
    },
    {
        id: '161',
        name: 'ሙምቲዕ ደርስ 161.mp3',
        type: 'audio',
        url: getDirectLink('11kCob5cMfDjaRsLXjlSbwFaGdmN-MsZ_'),
    },
    {
        id: '162',
        name: 'ሙምቲዕ ደርስ 162.mp3',
        type: 'audio',
        url: getDirectLink('1c7we8LMm5DkjJGvzrAZNWI2KJkOYPcf-'),
    },
    {
        id: '163',
        name: 'ሙምቲዕ ደርስ 163.mp3',
        type: 'audio',
        url: getDirectLink('1MkWhbBUb6KDHBMRwj6Q0uqNdZuiGcs9Y'),
    },
    {
        id: '164',
        name: 'ሙምቲዕ ደርስ 164.mp3',
        type: 'audio',
        url: getDirectLink('1se1xTBrJyMst1hgCndsMOo7m9wQBoWju'),
    },
    {
        id: '165',
        name: 'ሙምቲዕ ደርስ 165.mp3',
        type: 'audio',
        url: getDirectLink('17iBt8DebZWNQA4ntvF5tB1y0ixORGHfU'),
    },
    {
        id: '166',
        name: 'ሙምቲዕ ደርስ 166.mp3',
        type: 'audio',
        url: getDirectLink('1Qi0LRB-OxgKFaoXI61GyrUfU_rXi2jzv'),
    },
    {
        id: '167',
        name: 'ሙምቲዕ ደርስ 167.mp3',
        type: 'audio',
        url: getDirectLink('1zK8w44fY27ajNeEMIMQmWxA9xiPqdKdc'),
    },
    {
        id: '168',
        name: 'ሙምቲዕ ደርስ 168.mp3',
        type: 'audio',
        url: getDirectLink('1F4dfBHSv0WtiV-XM8PCQkv8sGmvoeyb0'),
    },
    {
        id: '169',
        name: 'ሙምቲዕ ደርስ 169.mp3',
        type: 'audio',
        url: getDirectLink('1NskgOiBQWvpo6NLijtMgCkYNSuRdBR8R'),
    },
    {
        id: '170',
        name: 'ሙምቲዕ ደርስ 170.mp3',
        type: 'audio',
        url: getDirectLink('1Kuu1cOC7pqr55aTrZnQJOLz1Ho_dW-8p'),
    },
    {
        id: '171',
        name: 'ሙምቲዕ ደርስ 171.mp3',
        type: 'audio',
        url: getDirectLink('11rxdZPqr2GwjfauLlgeNEExgFVV1dX0n'),
    },
    {
        id: '172',
        name: 'ሙምቲዕ ደርስ 172.mp3',
        type: 'audio',
        url: getDirectLink('1-iBTknlBLLjPSneVryljnCbGJBe0Osyx'),
    },
    {
        id: '173',
        name: 'ሙምቲዕ ደርስ 173.mp3',
        type: 'audio',
        url: getDirectLink('13UGm2_EJnHIwDZc5RUjbh6_2RXlfj3k7'),
    },
    {
        id: '174',
        name: 'ሙምቲዕ ደርስ 174.mp3',
        type: 'audio',
        url: getDirectLink('1Kk2XUtjkMEFfPw_ePAsRZa9Jo22MYc9t'),
    },
    {
        id: '175A',
        name: 'ሙምቲዕ ደርስ 175A.mp3',
        type: 'audio',
        url: getDirectLink('1LqAi9vZ9RypU-eI3IHSPtR-wD_6L2hNo'),
    },
    {
        id: '175B',
        name: 'ሙምቲዕ ደርስ 175B.mp3',
        type: 'audio',
        url: getDirectLink('1T1DM6KgIvcdjxvQREBtGLUXISK_z6xz9'),
    },
    {
        id: '176',
        name: 'ሙምቲዕ ደርስ 176.mp3',
        type: 'audio',
        url: getDirectLink('1WB8kSF3yX3wujDvllGdZtULcqzcSdinO'),
    },
    {
        id: '177',
        name: 'ሙምቲዕ ደርስ 177.mp3',
        type: 'audio',
        url: getDirectLink('1oLrEAOBTNWZJpciN2hVWpVzanvhNA481'),
    },
    {
        id: '178',
        name: 'ሙምቲዕ ደርስ 178.mp3',
        type: 'audio',
        url: getDirectLink('1SvgTywQr5ZvDFxKJhAA6j53WDY6QFXsA'),
    },
    {
        id: '179',
        name: 'ሙምቲዕ ደርስ 179.mp3',
        type: 'audio',
        url: getDirectLink('1hZGeCbQdYESdJYRZV9ind-1p04_Ii0Ou'),
    },
    {
        id: '180',
        name: 'ሙምቲዕ ደርስ 180.mp3',
        type: 'audio',
        url: getDirectLink('1heLlI_jLZa30dKZ5UKQKefs-YJhKDkaW'),
    },
    {
        id: '181',
        name: 'ሙምቲዕ ደርስ 181.mp3',
        type: 'audio',
        url: getDirectLink('11n736sgZ6odIZpTgEQsg0VFwKFClTfX6'),
    },
    {
        id: '182',
        name: 'ሙምቲዕ ደርስ 182.mp3',
        type: 'audio',
        url: getDirectLink('19WbaRKAHg9EdAVsa-tWTHYdzdVgamXKK'),
    },
    {
        id: '183',
        name: 'ሙምቲዕ ደርስ 183.mp3',
        type: 'audio',
        url: getDirectLink('1yEqb8VN2o2tWyvBfIck0t9fRQsNeQAwb'),
    },
    {
        id: '184',
        name: 'ሙምቲዕ ደርስ 184.mp3',
        type: 'audio',
        url: getDirectLink('18s_mzPI-1KrtYP7O-dXoOYbF4O9wBPBu'),
    },
    {
        id: '185',
        name: 'ሙምቲዕ ደርስ 185.mp3',
        type: 'audio',
        url: getDirectLink('1G78FwtmL7e5DSIMejZclhmuw0OtLjUcR'),
    },
    {
        id: '186',
        name: 'ሙምቲዕ ደርስ 186.mp3',
        type: 'audio',
        url: getDirectLink('1ojktWdaR7T9Vn2YqQoycCZX_WFayXULP'),
    },
    {
        id: '187',
        name: 'ሙምቲዕ ደርስ 187.mp3',
        type: 'audio',
        url: getDirectLink('1-ob38RDKd9tNEelkaDVKyOcUQeWTpISy'),
    },
    {
        id: '188',
        name: 'ሙምቲዕ ደርስ 188.mp3',
        type: 'audio',
        url: getDirectLink('1ofVUiGcBwxgeJmbNQk3wI7_P0GuqQfyW'),
    },
    {
        id: '189',
        name: 'ሙምቲዕ ደርስ 189.mp3',
        type: 'audio',
        url: getDirectLink('18Ga-xT73KbXu-u1Qu9OfsCNZ0ggCA4fE'),
    },
    {
        id: '190',
        name: 'ሙምቲዕ ደርስ 190.mp3',
        type: 'audio',
        url: getDirectLink('1i3Bq5CnAz0pAfvSUmglWcwxT2gM-eIwI'),
    },
    {
        id: '191',
        name: 'ሙምቲዕ ደርስ 191.mp3',
        type: 'audio',
        url: getDirectLink('114PDedUaquN1Q0fV9JLqYIkPPBm3lEMX'),
    },
    {
        id: '192',
        name: 'ሙምቲዕ ደርስ 192.mp3',
        type: 'audio',
        url: getDirectLink('192sYpR-FUIK9Xqt4fmAEBi6pJxzLFS3K'),
    },
    {
        id: '193',
        name: 'ሙምቲዕ ደርስ 193.mp3',
        type: 'audio',
        url: getDirectLink('1Uk6Qx6BVNKXcdh9eWB47hf8M2DQpGTZb'),
    },
    {
        id: '194',
        name: 'ሙምቲዕ ደርስ 194.mp3',
        type: 'audio',
        url: getDirectLink('1JJafDkZDwZjfsnv06nyU6rpXRo-v1VX_'),
    },
    {
        id: '195',
        name: 'ሙምቲዕ ደርስ 195.mp3',
        type: 'audio',
        url: getDirectLink('1VEomKEQYRdLu5MpYaPvuZLuPCjJPS1WP'),
    },
    {
        id: '196',
        name: 'ሙምቲዕ ደርስ 196.mp3',
        type: 'audio',
        url: getDirectLink('1yyZEueUIn2DqbSEDP9NgF4TPPjf07vTp'),
    },
    {
        id: '197',
        name: 'ሙምቲዕ ደርስ 197.mp3',
        type: 'audio',
        url: getDirectLink('1hjBp4zCevSJf0cuA0jmMBCc32ZhRY-Dr'),
    },
    {
        id: '198',
        name: 'ሙምቲዕ ደርስ 198.mp3',
        type: 'audio',
        url: getDirectLink('1WTqyDuAaSRyqcRisjTIgMB1ZKUh1MsQf'),
    },
    {
        id: '199',
        name: 'ሙምቲዕ ደርስ 199.mp3',
        type: 'audio',
        url: getDirectLink('1_3HNGKq_JtR8Q4SDMfA2w_40Xh1n6UEE'),
    },
    {
        id: '200',
        name: 'ሙምቲዕ ደርስ 200.mp3',
        type: 'audio',
        url: getDirectLink('1x5hZKhMo84CW_2MZMYKfQOpeHwbWaEy9'),
    },
    {
        id: '201',
        name: 'ሙምቲዕ ደርስ 201.mp3',
        type: 'audio',
        url: getDirectLink('1M7AgyJXvaSGahmaKef6G5jCeQflwP-Hl'),
    },
    {
        id: '202',
        name: 'ሙምቲዕ ደርስ 202.mp3',
        type: 'audio',
        url: getDirectLink('1xN4-a83isTRRbJorm1iml6qGQhlU3vuC'),
    }
];

const MUSTALAH_FILES: DriveFile[] = [
    {
        id: 'mustalah-pdf',
        name: 'ሙስጠለሑል ሓዲስ.pdf',
        type: 'pdf',
        url: getDirectLink('1klVmhnq0YyWqcE7TS2801MxawO3t8u1n'),
    },
    { id: 'mustalah-1', name: 'ሙስጠለሑል ሓዲስ ደርስ 1.mp3', type: 'audio', url: getDirectLink('16Qqh9lz4KVLD4ZnMdWJcdvt0na6fFJCQ') },
    { id: 'mustalah-2', name: 'ሙስጠለሑል ሓዲስ ደርስ 2.mp3', type: 'audio', url: getDirectLink('1RnwDjz8ouq0D93NoYFQDohDL4MIRLfam') },
    { id: 'mustalah-3', name: 'ሙስጠለሑል ሓዲስ ደርስ 3.mp3', type: 'audio', url: getDirectLink('1_ET4-x3BlWBiRp3SQla-KQTWnh9Zgp7A') },
    { id: 'mustalah-4', name: 'ሙስጠለሑል ሓዲስ ደርስ 4.mp3', type: 'audio', url: getDirectLink('1T0zNdKw-pAo8dHTk0OEwCtWRjLepqxHt') },
    { id: 'mustalah-5', name: 'ሙስጠለሑል ሓዲስ ደርስ 5.mp3', type: 'audio', url: getDirectLink('1nkaj_0TgTi_DL-ArbHEthLm7_3W8bZma') },
    { id: 'mustalah-6', name: 'ሙስጠለሑል ሓዲስ ደርስ 6.mp3', type: 'audio', url: getDirectLink('1qQ9sn4nuSqplm_4CoHNX_l6TpjGs9R9a') },
    { id: 'mustalah-7', name: 'ሙስጠለሑል ሓዲስ ደርስ 7.mp3', type: 'audio', url: getDirectLink('12Ue-iqQk6iL8LtxK5q-x_pFGjzMPwK7a') },
    { id: 'mustalah-8', name: 'ሙስጠለሑል ሓዲስ ደርስ 8.mp3', type: 'audio', url: getDirectLink('1QdC-HotS2VbwuGACJRX5ucsYBwr_9PmX') },
    { id: 'mustalah-9', name: 'ሙስጠለሑል ሓዲስ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1t4wAdGuZSnTRvmQw2TEX29niAFPLUQ8B') },
    { id: 'mustalah-10', name: 'ሙስጠለሑል ሓዲስ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1zR_24j_6cPeBCjfafVQEOiHtP3Ub4l1d') },
    { id: 'mustalah-11', name: 'ሙስጠለሑል ሓዲስ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1tjL_UPoM1q3ySdde5jwWduXyOJT68oso') },
    { id: 'mustalah-12', name: 'ሙስጠለሑል ሓዲስ ደርስ 12.mp3', type: 'audio', url: getDirectLink('1srn8diz8e8DjPjhd7sXk6FhPCF71Zbtt') },
    { id: 'mustalah-13', name: 'ሙስጠለሑል ሓዲስ ደርስ 13.mp3', type: 'audio', url: getDirectLink('1dkzaKqrgXYfJWk15ETM7TCD19YpHrGxB') },
    { id: 'mustalah-14', name: 'ሙስጠለሑል ሓዲስ ደርስ 14.mp3', type: 'audio', url: getDirectLink('1BOhBbNIfLkm67yg7Bp0zgLb3rc8TbZpe') },
    { id: 'mustalah-15', name: 'ሙስጠለሑል ሓዲስ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1U3cpcxGHCmb1HzCgasSdGHCnHBF_1C2R') },
    { id: 'mustalah-16', name: 'ሙስጠለሑል ሓዲስ ደርስ 16.mp3', type: 'audio', url: getDirectLink('1lD0h5jcB4sJwiVDAOpuHqKKB1E85FOdn') },
    { id: 'mustalah-17', name: 'ሙስጠለሑል ሓዲስ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1aTCU2iLwY_JfGqZDZO9fmpW2jVU8PTEr') },
    { id: 'mustalah-18', name: 'ሙስጠለሑል ሓዲስ ደርስ 18.mp3', type: 'audio', url: getDirectLink('1_vzOH0ZyPXTE-3jkNZeXdmq2pdGLsEyr') },
    { id: 'mustalah-19', name: 'ሙስጠለሑል ሓዲስ ደርስ 19.mp3', type: 'audio', url: getDirectLink('1nNoOUMWikCKE6apqjVCD_Kepf5FAwpZ7') },
    { id: 'mustalah-20', name: 'ሙስጠለሑል ሓዲስ ደርስ 20.mp3', type: 'audio', url: getDirectLink('117RXufDed9wYsg3FkiX-YbwTX47OQglp') },
    { id: 'mustalah-21', name: 'ሙስጠለሑል ሓዲስ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1aP1ST6J3KfIm7hKW6vTIUoT__qc8NaeA') },
    { id: 'mustalah-22', name: 'ሙስጠለሑል ሓዲስ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1nlZsQL6h856dgXcakFybDacwbR5bfuLD') },
    { id: 'mustalah-23', name: 'ሙስጠለሑል ሓዲስ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1azLsoeBoKzX7NN3s_eojDgVG2JrS6q5R') },
    { id: 'mustalah-24', name: 'ሙስጠለሑል ሓዲስ ደርስ 24.mp3', type: 'audio', url: getDirectLink('19KTSqoONZhNlflZfaeh-2FL-YlmblTmb') },
    { id: 'mustalah-25', name: 'ሙስጠለሑል ሓዲስ ደርስ 25.mp3', type: 'audio', url: getDirectLink('1_6IBhiFEOGkveAyuGfSyWTR1wFDHawwS') },
    { id: 'mustalah-26', name: 'ሙስጠለሑል ሓዲስ ደርስ 26.mp3', type: 'audio', url: getDirectLink('1U7Z53CksRPtaUR57HeJAZENAgHlBELx2') },
    { id: 'mustalah-27', name: 'ሙስጠለሑል ሓዲስ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1IIbJA7W7mWg8YtxD-VHFaIK8kV0-3caa') },
    { id: 'mustalah-28', name: 'ሙስጠለሑል ሓዲስ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1fSbQ4SRCMcgPzHo87RDLZto_49HBEAWJ') },
    { id: 'mustalah-29', name: 'ሙስጠለሑል ሓዲስ ደርስ 29.mp3', type: 'audio', url: getDirectLink('1gRQLdn68KpC7fRNGUGrd5qO35DSD5S6f') },
    { id: 'mustalah-30', name: 'ሙስጠለሑል ሓዲስ ደርስ 30.mp3', type: 'audio', url: getDirectLink('1VsMWfWjdi6gztiesQOFUFmaQHmcIooeK') },
    { id: 'mustalah-31', name: 'ሙስጠለሑል ሓዲስ ደርስ 31.mp3', type: 'audio', url: getDirectLink('1HpZffPBZjMgxdjSKe9FGJ7935WunKSiw') },
    { id: 'mustalah-32', name: 'ሙስጠለሑል ሓዲስ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1wzk126ZOpMVUI7pPTXayjNsji2-Oq7l5') },
    { id: 'mustalah-33', name: 'ሙስጠለሑል ሓዲስ ደርስ 33.mp3', type: 'audio', url: getDirectLink('17AdiI3d9nWWwv4KvQyZVQdi46TkjeMop') },
    { id: 'mustalah-34', name: 'ሙስጠለሑል ሓዲስ ደርስ 34.mp3', type: 'audio', url: getDirectLink('1uZ3igd6Jk56hezVTASEmt0yJ6vnsJdXO') },
    { id: 'mustalah-35', name: 'ሙስጠለሑል ሓዲስ ደርስ 35.mp3', type: 'audio', url: getDirectLink('1WqvwfbhXEWt-FLQxEai5u5iC9g9nyQ48') },
    { id: 'mustalah-36', name: 'ሙስጠለሑል ሓዲስ ደርስ 36.mp3', type: 'audio', url: getDirectLink('1t0QUjxu3zr99N2MdE5UGwXIxJU2zllBc') },
    { id: 'mustalah-37', name: 'ሙስጠለሑል ሓዲስ ደርስ 37.mp3', type: 'audio', url: getDirectLink('14Iva8QPDpwogZfKTx_JZ4No3p2s05e6A') },
    { id: 'mustalah-38', name: 'ሙስጠለሑል ሓዲስ ደርስ 38.mp3', type: 'audio', url: getDirectLink('1USbG67nPhSx2Eqmdut2X6yOJLIhhYWhm') },
    { id: 'mustalah-39', name: 'ሙስጠለሑል ሓዲስ ደርስ 39.mp3', type: 'audio', url: getDirectLink('1chNXTFw7DR8lPPjvBeRDjPbIOxr_Ys2k') },
    { id: 'mustalah-40', name: 'ሙስጠለሑል ሓዲስ ደርስ 40.mp3', type: 'audio', url: getDirectLink('1pLeDfG7UouXTPQSlgI5jwj6wtFdVO5sw') },
    { id: 'mustalah-41', name: 'ሙስጠለሑል ሓዲስ ደርስ 41.mp3', type: 'audio', url: getDirectLink('1Zyh9PnI03FGI5jf-95i7i2WK4X676uVy') },
    { id: 'mustalah-42', name: 'ሙስጠለሑል ሓዲስ ደርስ 42.mp3', type: 'audio', url: getDirectLink('13Ehz-JjfomuNt2dKVBLht6SKvGSri6_L') },
    { id: 'mustalah-43', name: 'ሙስጠለሑል ሓዲስ ደርስ 43.mp3', type: 'audio', url: getDirectLink('1pA9yWyh_UfvUOGmhPu6OwCBFllhdRpzW') },
    { id: 'mustalah-44', name: 'ሙስጠለሑል ሓዲስ ደርስ 44.mp3', type: 'audio', url: getDirectLink('1BH7cWSZ1HzHonv1ppISQrTIVb_HL_iwq') },
    { id: 'mustalah-45', name: 'ሙስጠለሑል ሓዲስ ደርስ 45.mp3', type: 'audio', url: getDirectLink('1rSv-LNXLfh3HSkZr3bJYlhJD5png6xLs') },
    { id: 'mustalah-46', name: 'ሙስጠለሑል ሓዲስ ደርስ 46.mp3', type: 'audio', url: getDirectLink('1139tUaUPrrSkBp6QFlG6OuEUcJbGIc0K') },
    { id: 'mustalah-47', name: 'ሙስጠለሑል ሓዲስ ደርስ 47.mp3', type: 'audio', url: getDirectLink('11MXYqH4MFag6MgRkqxpuU0q5voT5LgvE') },
    { id: 'mustalah-48', name: 'ሙስጠለሑል ሓዲስ ደርስ 48.mp3', type: 'audio', url: getDirectLink('1vbkMP8An-aX5HP8c8C9zsyNJcf7qOFee') },
    { id: 'mustalah-49', name: 'ሙስጠለሑል ሓዲስ ደርስ 49.mp3', type: 'audio', url: getDirectLink('1LCWUXUYPMAVYm918wdEhs_YVvRo3effl') },
    { id: 'mustalah-50', name: 'ሙስጠለሑል ሓዲስ ደርስ 50.mp3', type: 'audio', url: getDirectLink('1YcFVl2zNKN_P5ZBAMoquTkofr91atedk') },
    { id: 'mustalah-51', name: 'ሙስጠለሑል ሓዲስ ደርስ 51.mp3', type: 'audio', url: getDirectLink('1bS23aCHT0rPlB9aJM_VjPkI0H2a-9oi7') },
    { id: 'mustalah-52', name: 'ሙስጠለሑል ሓዲስ ደርስ 52.mp3', type: 'audio', url: getDirectLink('19xSXFn38s0-iSay65Lc4Lt3juJFAsmVy') },
    { id: 'mustalah-53', name: 'ሙስጠለሑል ሓዲስ ደርስ 53.mp3', type: 'audio', url: getDirectLink('1AV2HIzYmQ6vcS38P5b6ugGfFjJc3p1vv') },
    { id: 'mustalah-54', name: 'ሙስጠለሑል ሓዲስ ደርስ 54.mp3', type: 'audio', url: getDirectLink('1dsvNO22pOcBU2SQ48RyqN4kTOR76UMtX') },
    { id: 'mustalah-55', name: 'ሙስጠለሑል ሓዲስ ደርስ 55.mp3', type: 'audio', url: getDirectLink('1HBkDtxpYNUAQik_uXUL_k9m0oOBa5T-Z') },
    { id: 'mustalah-56', name: 'ሙስጠለሑል ሓዲስ ደርስ 56.mp3', type: 'audio', url: getDirectLink('1A4Ynih2yQUq5e21CgqdxHBlwtCH-YBA6') },
    { id: 'mustalah-57', name: 'ሙስጠለሑል ሓዲስ ደርስ 57.mp3', type: 'audio', url: getDirectLink('1O1RK9nCvvx63imLQHulRE2VGNoouOa0K') },
    { id: 'mustalah-58', name: 'ሙስጠለሑል ሓዲስ ደርስ 58.mp3', type: 'audio', url: getDirectLink('1xTqLHTH_zVk6LlA4VR0dVcxpkNduttUN') },
    { id: 'mustalah-59', name: 'ሙስጠለሑል ሓዲስ ደርስ 59.mp3', type: 'audio', url: getDirectLink('1KG2g5ULIkfDsdUb_ofPwZCQ_Xkk_K0RH') },
    { id: 'mustalah-60', name: 'ሙስጠለሑል ሓዲስ ደርስ 60.mp3', type: 'audio', url: getDirectLink('1iPs3BplZOtjP1uf4V6s-mSuadfg8Lk_E') },
    { id: 'mustalah-61', name: 'ሙስጠለሑል ሓዲስ ደርስ 61.mp3', type: 'audio', url: getDirectLink('1jgmmrX1TywSudWW6S_eZogU8SPjPh_S_') },
    { id: 'mustalah-62', name: 'ሙስጠለሑል ሓዲስ ደርስ 62.mp3', type: 'audio', url: getDirectLink('1Ppbq0XHpbvBlc0n04yP1h6p1MKeuLa1c') },
    { id: 'mustalah-63', name: 'ሙስጠለሑል ሓዲስ ደርስ 63.mp3', type: 'audio', url: getDirectLink('1L0VW9bcP-zy2who8LodTuw3jNuppHokT') },
    { id: 'mustalah-64A', name: 'ሙስጠለሑል ሓዲስ ደርስ 64A.mp3', type: 'audio', url: getDirectLink('1gv7jHP5c0H254dQQH2CRxL8njwt7bz9z') },
    { id: 'mustalah-64B', name: 'ሙስጠለሑል ሓዲስ ደርስ 64B.mp3', type: 'audio', url: getDirectLink('1MJgzrgkyi895GZV7N7eGL8Z1WOTBmbzI') },
    { id: 'mustalah-65', name: 'ሙስጠለሑል ሓዲስ ደርስ 65.mp3', type: 'audio', url: getDirectLink('1P-v1arUtsuMyJ5oWL2qtBf4UZukjkyu3') },
    { id: 'mustalah-66', name: 'ሙስጠለሑል ሓዲስ ደርስ 66.mp3', type: 'audio', url: getDirectLink('1SkcBJGZN5B_eX2jW3GkkGNEMLmxe7Mjr') },
    { id: 'mustalah-67', name: 'ሙስጠለሑል ሓዲስ ደርስ 67.mp3', type: 'audio', url: getDirectLink('1ixxCllakXSKfr1W4sQm79RhC_eCCHiKw') },
    { id: 'mustalah-68', name: 'ሙስጠለሑል ሓዲስ ደርስ 68.mp3', type: 'audio', url: getDirectLink('10Y7wOk3XdqTfbAtsc8eNT1YAA7rcP8KK') },
    { id: 'mustalah-69', name: 'ሙስጠለሑል ሓዲስ ደርስ 69.mp3', type: 'audio', url: getDirectLink('1s4zW4DRbDh7cjKqqnPTtzkmMteJEhHgH') },
    { id: 'mustalah-70', name: 'ሙስጠለሑል ሓዲስ ደርስ 70.mp3', type: 'audio', url: getDirectLink('16Flc2sRhsSglu8HOzzGHvljFQEz2n3S-') },
    { id: 'mustalah-71', name: 'ሙስጠለሑል ሓዲስ ደርስ 71.mp3', type: 'audio', url: getDirectLink('1RZ81oNA782yW2yGffHHyUATRarVyJnDn') },
    { id: 'mustalah-72', name: 'ሙስጠለሑል ሓዲስ ደርስ 72.mp3', type: 'audio', url: getDirectLink('1o3V2Mhhjfgf2tBIGtT0ETj1c3NunlwHL') },
    { id: 'mustalah-73', name: 'ሙስጠለሑል ሓዲስ ደርስ 73.mp3', type: 'audio', url: getDirectLink('1tS1Ot8EzPdaRty0Mn2Hm8VIl2D1WhKzv') },
    { id: 'mustalah-74', name: 'ሙስጠለሑል ሓዲስ ደርስ 74.mp3', type: 'audio', url: getDirectLink('1Z0tBI7ItW4i86QY_3KCzkWFmH9gEH7c4') },
    { id: 'mustalah-75A', name: 'ሙስጠለሑል ሓዲስ ደርስ 75A.mp3', type: 'audio', url: getDirectLink('1nPrIO25bfrii4pjvsMRMaLCZD9L-JzgL') },
    { id: 'mustalah-75B', name: 'ሙስጠለሑል ሓዲስ ደርስ 75B.mp3', type: 'audio', url: getDirectLink('1M1vTv4EUps2zEMjZbGa5GfzqX--lTJ89') },
    { id: 'mustalah-76', name: 'ሙስጠለሑል ሓዲስ ደርስ 76.mp3', type: 'audio', url: getDirectLink('1kf9Usx8hTlO62ZnYhthOoRA6HkMHCQda') },
    { id: 'mustalah-77', name: 'ሙስጠለሑል ሓዲስ ደርስ 77.mp3', type: 'audio', url: getDirectLink('1Z4CTc_5S1lA-lEupyrFgj7lZt1jPy3Ep') },
    { id: 'mustalah-78', name: 'ሙስጠለሑል ሓዲስ ደርስ 78.mp3', type: 'audio', url: getDirectLink('1hBr6RgTTdUe82yq_TDs5TDj-Wneyl99Q') },
    { id: 'mustalah-79', name: 'ሙስጠለሑል ሓዲስ ደርስ 79.mp3', type: 'audio', url: getDirectLink('1HqA866Ffbro1GiNO1GOSY69TM5Id1goD') },
    { id: 'mustalah-80', name: 'ሙስጠለሑል ሓዲስ ደርስ 80.mp3', type: 'audio', url: getDirectLink('19Ndc_JdPKVF6FAMKIicCcSS9_QYNiS7P') },
    { id: 'mustalah-81', name: 'ሙስጠለሑል ሓዲስ ደርስ 81.mp3', type: 'audio', url: getDirectLink('1N51CLFA0Ge7git2Jdt1JgqO4Efpfl0OA') },
    { id: 'mustalah-82', name: 'ሙስጠለሑል ሓዲስ ደርስ 82.mp3', type: 'audio', url: getDirectLink('1fWSJnvfLkwZs_LaWmqlHCRF3nfwwJlNg') },
    { id: 'mustalah-83', name: 'ሙስጠለሑል ሓዲስ ደርስ 83.mp3', type: 'audio', url: getDirectLink('1TT3eum1pQ7fQGkdiiEznZ6_eauqAqhMa') },
    { id: 'mustalah-84', name: 'ሙስጠለሑል ሓዲስ ደርስ 84.mp3', type: 'audio', url: getDirectLink('1OMxROCeVJC3w52GztxQqn6-q8ivkneox') },
    { id: 'mustalah-85', name: 'ሙስጠለሑል ሓዲስ ደርስ 85.mp3', type: 'audio', url: getDirectLink('1Gt6kYIJI7OKqxR7N0LzRnPMaSb8pVbo7') },
    { id: 'mustalah-86', name: 'ሙስጠለሑል ሓዲስ ደርስ 86.mp3', type: 'audio', url: getDirectLink('17RkDpHer0QxeKT-gQhn6RCnm9rLaABzy') },
    { id: 'mustalah-87', name: 'ሙስጠለሑል ሓዲስ ደርስ 87.mp3', type: 'audio', url: getDirectLink('1-RWhGSsUCXM3AjvaXIKuc6EfsXd-g_8j') },
];

export const CATEGORIES: Category[] = [
    {
        id: 'mumtic',
        title: 'ሙምቲዕ ደርስ',
        description: 'በ ኡስታዝ አቡ ጁወይሪያ የቀረበ',
        files: MUMTIC_FILES,
    },
    {
        id: 'mustalah',
        title: 'ሙስጠለሑል ሓዲስ',
        description: 'በ ኡስታዝ አቡ ጁወይሪያ የቀረበ',
        files: MUSTALAH_FILES,
    }
];

// For backward compatibility while refactoring other components
export const DRIVE_FILES = MUMTIC_FILES;
export const ALL_FILES = MUMTIC_FILES;

