import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const MUTEMIMETUL_UJRUMYA_FILES: DriveFile[] = [
    {
        id: 'mutemimetul-ujrumya-pdf',
        name: 'ሙተሚመቱል ኡጅሩምያ.pdf',
        type: 'pdf',
        url: getDirectLink('1JiXqaydDjm8X-UFRhkVOUDuzb2m4k7U-'),
    },
    { id: 'mutemimetul-ujrumya-1', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 1.mp3', type: 'audio', url: getDirectLink('1wzq4n78adc3CgBuew3zVii4BEQvQ_prc') },
    { id: 'mutemimetul-ujrumya-2', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 2.mp3', type: 'audio', url: getDirectLink('1S-Cjd18wAJwUJYhZiPow4sm444J5wrCv') },
    { id: 'mutemimetul-ujrumya-3', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 3.mp3', type: 'audio', url: getDirectLink('1Tzu_Lt1CksyyOE7lxOKsIaWOTg-A4QG4') },
    { id: 'mutemimetul-ujrumya-4', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 4.mp3', type: 'audio', url: getDirectLink('1eHY8qtfxn38Vmy7E7WSyD0Uy4u-P1c_j') },
    { id: 'mutemimetul-ujrumya-5', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 5.mp3', type: 'audio', url: getDirectLink('1d0QykBqlXAGbDGFd6nJYxByIvPwdMroR') },
    { id: 'mutemimetul-ujrumya-6', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 6.mp3', type: 'audio', url: getDirectLink('1yj3rVlmWOQctLqEUrfKfw0GVmTzVAiUH') },
    { id: 'mutemimetul-ujrumya-7', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 7.mp3', type: 'audio', url: getDirectLink('1g6OIkEqVKKTSlQw1T-LAoSHms35QRRQt') },
    { id: 'mutemimetul-ujrumya-8', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 8.mp3', type: 'audio', url: getDirectLink('1M6MWq9KbDXFhSShoj5xmZhVxcZnZT8zr') },
    { id: 'mutemimetul-ujrumya-9', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 9.mp3', type: 'audio', url: getDirectLink('1MwwrShIo-huRqS8DpyzhZQrYGTLyj6CB') },
    { id: 'mutemimetul-ujrumya-10', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 10.mp3', type: 'audio', url: getDirectLink('1285FkT-u29DSL9_MvltMlCQreTm4uLe8') },
    { id: 'mutemimetul-ujrumya-11', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 11.mp3', type: 'audio', url: getDirectLink('1wFoRmzmRaw4FATKt57p2XUn3TQHTyKtS') },
    { id: 'mutemimetul-ujrumya-12', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 12.mp3', type: 'audio', url: getDirectLink('1cAC6T3EpcGgjaOTRFyL7AHK1APxQj_jy') },
    { id: 'mutemimetul-ujrumya-13', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 13.mp3', type: 'audio', url: getDirectLink('13m3OknrPLPffEcJ_wBxFoV7MmfmNvLME') },
    { id: 'mutemimetul-ujrumya-14', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 14.mp3', type: 'audio', url: getDirectLink('1grmhKwEhA-XInJXqkwRsNsZ1at-ZaVaH') },
    { id: 'mutemimetul-ujrumya-15', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 15.mp3', type: 'audio', url: getDirectLink('1rZdPo1jKPRTb7_GD8p8YR6GmXyHP4DwR') },
    { id: 'mutemimetul-ujrumya-16', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 16.mp3', type: 'audio', url: getDirectLink('1tu6XJqkGOIPd9Ic7FtP-ifFa2ZPoJ2tP') },
    { id: 'mutemimetul-ujrumya-17', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 17.mp3', type: 'audio', url: getDirectLink('1Q3rmxIFlZToqVloXwXcfMSQ8lGHZaHo3') },
    { id: 'mutemimetul-ujrumya-18', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 18.mp3', type: 'audio', url: getDirectLink('1Ri9Ns_R9FLiDy6_VKHmIq7ul2j0y89in') },
    { id: 'mutemimetul-ujrumya-19', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 19.mp3', type: 'audio', url: getDirectLink('1B4rhuwMZyP8MFPcUj5z0PMBtOkW5zctH') },
    { id: 'mutemimetul-ujrumya-20', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 20.mp3', type: 'audio', url: getDirectLink('1Qbt-9DbFDtH4ngqq9EFtefV2k6PBz5co') },
    { id: 'mutemimetul-ujrumya-21', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 21.mp3', type: 'audio', url: getDirectLink('1ZPOoaOGwBtKy1L5ufktmUgGb6Z5VYvuL') },
    { id: 'mutemimetul-ujrumya-22', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 22.mp3', type: 'audio', url: getDirectLink('1GgjrSqc1TtRGnl9NfdSHZJMntkAL4Fl0') },
    { id: 'mutemimetul-ujrumya-23', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 23.mp3', type: 'audio', url: getDirectLink('1YfYFBAU1PeuMlUrOFKLnpI427gyoF6i-') },
    { id: 'mutemimetul-ujrumya-24', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 24.mp3', type: 'audio', url: getDirectLink('1eAXilzN2pJYlCzEfI2M7FUlKjU7r9XG6') },
    { id: 'mutemimetul-ujrumya-25', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 25.mp3', type: 'audio', url: getDirectLink('1oR6GNkN0VoIu-Sskms-m8644iSAdkHE-') },
    { id: 'mutemimetul-ujrumya-26', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 26.mp3', type: 'audio', url: getDirectLink('1ki4ujCCxK7rN07SY_QoHsxIWxpiVEdR5') },
    { id: 'mutemimetul-ujrumya-27', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 27.mp3', type: 'audio', url: getDirectLink('1bRXDIYxKnJ3omp_OSKAYyQJyA4KVW1PW') },
    { id: 'mutemimetul-ujrumya-28', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 28.mp3', type: 'audio', url: getDirectLink('1FhRURh9mHSyT4WF4-BHNzqQt0FU0zu9m') },
    { id: 'mutemimetul-ujrumya-29', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 29.mp3', type: 'audio', url: getDirectLink('1NUiHJsqbxkUiu6DgHMSydhuFPIyQDWvz') },
    { id: 'mutemimetul-ujrumya-30', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 30.mp3', type: 'audio', url: getDirectLink('1pzbfZpKwEBSO51OemDzHWB6dIPo4HGxF') },
    { id: 'mutemimetul-ujrumya-31', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 31.mp3', type: 'audio', url: getDirectLink('17iObQWy0uefbMNOCbxgmegknTDa2exU3') },
    { id: 'mutemimetul-ujrumya-32', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 32.mp3', type: 'audio', url: getDirectLink('1Q8W5tig9W_Rrx0uodUiKaBfuRwRwuS5g') },
    { id: 'mutemimetul-ujrumya-33', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 33.mp3', type: 'audio', url: getDirectLink('1VH_w2Ntb4d7Os5iTYbikOeW9hFxsrdSu') },
    { id: 'mutemimetul-ujrumya-34', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 34.mp3', type: 'audio', url: getDirectLink('1PfDzb5J0jJDtCJmxiP9TdvDr0NtYd-Zr') },
    { id: 'mutemimetul-ujrumya-35', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 35.mp3', type: 'audio', url: getDirectLink('1gESZFPRZE4Ly6mv14wZ0ay4domNOG6Ea') },
    { id: 'mutemimetul-ujrumya-36', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 36.mp3', type: 'audio', url: getDirectLink('1DZLyUj5sA7gtfnrooXJ7pVKhM9XdJNRq') },
    { id: 'mutemimetul-ujrumya-37', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 37.mp3', type: 'audio', url: getDirectLink('1qfycG_QVhZHa8zzyTAsqCOtZCvEuVelD') },
    { id: 'mutemimetul-ujrumya-38', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 38.mp3', type: 'audio', url: getDirectLink('1PhYJ4FVtkY6rTDDwjnyO2ul64N3V6-Ti') },
    { id: 'mutemimetul-ujrumya-39', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 39.mp3', type: 'audio', url: getDirectLink('1xTPGC20Npg6sCSpAodEvCI9NJ-PGNQOv') },
    { id: 'mutemimetul-ujrumya-40', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 40.mp3', type: 'audio', url: getDirectLink('1WR6UHZHjfsh75Z1kGGJwgpiTKcmcS3r8') },
    { id: 'mutemimetul-ujrumya-41', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 41.mp3', type: 'audio', url: getDirectLink('19FBpiybKI4efe2BC0l-dXisAZCvMXQdO') },
    { id: 'mutemimetul-ujrumya-42', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 42.mp3', type: 'audio', url: getDirectLink('14dEQvso06RI6BYu6Iv_nPqBt14WyHD4-') },
    { id: 'mutemimetul-ujrumya-43', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 43.mp3', type: 'audio', url: getDirectLink('1GuP24RUVbPI6Mtrhf2-UY7ugfsflqByx') },
    { id: 'mutemimetul-ujrumya-44', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 44.mp3', type: 'audio', url: getDirectLink('1z8VvUsjiFiHcXzcLE4EHUnkvDySnt0Lo') },
    { id: 'mutemimetul-ujrumya-45', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 45.mp3', type: 'audio', url: getDirectLink('1EL3PJYdf6rglk_CskOAIWseY7QnljkB0') },
    { id: 'mutemimetul-ujrumya-46', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 46.mp3', type: 'audio', url: getDirectLink('1fRftnnLWALJobOPqh7qHCj2W_ZFDp3l3') },
    { id: 'mutemimetul-ujrumya-47', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 47.mp3', type: 'audio', url: getDirectLink('1bpdOkDxYJvSEm7wn3PkD5vIX0vd8AEQV') },
    { id: 'mutemimetul-ujrumya-48', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 48.mp3', type: 'audio', url: getDirectLink('1aFwh74zrpbTZBdntZKmzMA88UeJfxEG9') },
    { id: 'mutemimetul-ujrumya-49', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 49.mp3', type: 'audio', url: getDirectLink('1x0Ai5D8hgl37KRnpEaC9D_vWw7t6u1Qx') },
    { id: 'mutemimetul-ujrumya-50', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 50.mp3', type: 'audio', url: getDirectLink('1fM_YqHynQEBEFhC3f0QyLSMdQX_bRHxi') },
    { id: 'mutemimetul-ujrumya-51', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 51.mp3', type: 'audio', url: getDirectLink('1Fh48GqHFWJOGfvp2AgiV-fSqt-a862cV') },
    { id: 'mutemimetul-ujrumya-52', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 52.mp3', type: 'audio', url: getDirectLink('1ghE1G3ad2pcCgf94wTd9MFvkgCOOCMK_') },
    { id: 'mutemimetul-ujrumya-53', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 53.mp3', type: 'audio', url: getDirectLink('1vMb3TTWSQWqwtYsSUIg8g-8JMvK4WyRy') },
    { id: 'mutemimetul-ujrumya-54', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 54.mp3', type: 'audio', url: getDirectLink('19d_TB_ZJQcadjo5BVR_2DBMLPDa7hZWi') },
    { id: 'mutemimetul-ujrumya-55', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 55.mp3', type: 'audio', url: getDirectLink('1W1m25CF7oKhAjmwScwqGDJo9y46l69Fi') },
    { id: 'mutemimetul-ujrumya-56', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 56.mp3', type: 'audio', url: getDirectLink('1vltltZiQl3q7oOBzXkNCLu9IV2ZCXU3Y') },
    { id: 'mutemimetul-ujrumya-57', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 57.mp3', type: 'audio', url: getDirectLink('1I4vFTLCHY9bmOwt6acheuMHaXH1mEiKe') },
    { id: 'mutemimetul-ujrumya-58', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 58.mp3', type: 'audio', url: getDirectLink('1YvleQqs4FO87bqTjzaCiLkjd_7dT-_J9') },
    { id: 'mutemimetul-ujrumya-59', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 59.mp3', type: 'audio', url: getDirectLink('1D3-B9ua2ZpSlZ0MqfTHmIzIlJJ6JnkBt') },
    { id: 'mutemimetul-ujrumya-60', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 60.mp3', type: 'audio', url: getDirectLink('1yKdStig3hWQJJhrYFxz2HwjphtSyX6rt') },
    { id: 'mutemimetul-ujrumya-61', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 61.mp3', type: 'audio', url: getDirectLink('1-f5VGzLvj130w4IpudWZ6pNPkPGIVZXl') },
    { id: 'mutemimetul-ujrumya-62', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 62.mp3', type: 'audio', url: getDirectLink('1FtzLesFZl2FjKKneZwnehP8zwLN9WN8h') },
    { id: 'mutemimetul-ujrumya-63', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 63.mp3', type: 'audio', url: getDirectLink('1lSDG00PxwDP6AIb1mRHj_NnmDM3GN-XK') },
    { id: 'mutemimetul-ujrumya-64', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 64.mp3', type: 'audio', url: getDirectLink('1xFolcK91bhUlNt3JfqlICUHJ9tBo2xno') },
    { id: 'mutemimetul-ujrumya-65', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 65.mp3', type: 'audio', url: getDirectLink('1Yj3skjb3Ccxt8rJs5ZDtUkp1Vxpya1RZ') },
    { id: 'mutemimetul-ujrumya-66', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 66.mp3', type: 'audio', url: getDirectLink('1rBlJ5at5Q0Sh0m471k0XwH_45CpshuuR') },
    { id: 'mutemimetul-ujrumya-67', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 67.mp3', type: 'audio', url: getDirectLink('1cPp26K3Y2tVCBZHTmuD_Fzrr494ty9OY') },
    { id: 'mutemimetul-ujrumya-68', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 68.mp3', type: 'audio', url: getDirectLink('1paIII54LdTkECezTjqWSSgBQ96Oxn6ri') },
    { id: 'mutemimetul-ujrumya-69', name: 'ሙተሚመቱል ኡጅሩምያ ደርስ 69.mp3', type: 'audio', url: getDirectLink('1XpXcggrthpC4wMUab5AkP8WB3zy2Jwhm') },
];
