import { DriveFile } from '../types';

const getDirectLink = (id: string) => `https://drive.google.com/uc?id=${id}&export=download`;

export const TENBIHAT_FILES: DriveFile[] = [
    {
        id: 'tenbihat-pdf',
        name: 'ተንቢሃት.pdf',
        type: 'pdf',
        url: getDirectLink('1Mxg5VozBV_qMCQUlmunKTkK43ZBpCUmX'),
    },
    { id: 'tenbihat-1', name: 'ተንቢሃት ደርስ 1.mp3', type: 'audio', url: getDirectLink('1nwBVsAVgKI20kqkVY_s-PRGyqOG4XH7x') },
    { id: 'tenbihat-2', name: 'ተንቢሃት ደርስ 2.mp3', type: 'audio', url: getDirectLink('13P2nafJlxeq_xuFFeGRZZvZ0dbla5hhz') },
    { id: 'tenbihat-3', name: 'ተንቢሃት ደርስ 3.mp3', type: 'audio', url: getDirectLink('1puwBTPkKiVCGsNcTGBCOJXCffVjVowiI') },
    { id: 'tenbihat-4', name: 'ተንቢሃት ደርስ 4.mp3', type: 'audio', url: getDirectLink('12ognIv5dWUNiRThO7v5GKt4Eos1k8_zQ') },
    { id: 'tenbihat-5', name: 'ተንቢሃት ደርስ 5.mp3', type: 'audio', url: getDirectLink('1qbIlqHuqPiaeyKsQTZiGOGa91vxRiusq') },
    { id: 'tenbihat-6', name: 'ተንቢሃት ደርስ 6.mp3', type: 'audio', url: getDirectLink('1qYTupULmH-3FNqYDN6UF-NqyBkpPwkgR') },
    { id: 'tenbihat-7', name: 'ተንቢሃት ደርስ 7.mp3', type: 'audio', url: getDirectLink('1XPmTHVsAMMYKvaUyW8MjIp-zA6VOuqFL') },
    { id: 'tenbihat-8', name: 'ተንቢሃት ደርስ 8.mp3', type: 'audio', url: getDirectLink('10UXiT_nnvAM0WocIAQCK8WZPawdPqpB_') },
    { id: 'tenbihat-9', name: 'ተንቢሃት ደርስ 9.mp3', type: 'audio', url: getDirectLink('1_Mw5nPlhalpSJ8EFLniSNa3AHyUlDi_W') },
    { id: 'tenbihat-10', name: 'ተንቢሃት ደርስ 10.mp3', type: 'audio', url: getDirectLink('1GTGaKfUJK3RCUJ3QVaJaWZfzMAaM1xiB') },
    { id: 'tenbihat-11', name: 'ተንቢሃት ደርስ 11.mp3', type: 'audio', url: getDirectLink('1SltvWOYbBcO7Kqw0lU4RLbcHy7VwRCPK') },
    { id: 'tenbihat-12', name: 'ተንቢሃት ደርስ 12.mp3', type: 'audio', url: getDirectLink('1t8Cl_TRr0eZYDdXNssir4mZkcSiSMQZf') },
    { id: 'tenbihat-13', name: 'ተንቢሃት ደርስ 13.mp3', type: 'audio', url: getDirectLink('1if639LNYr-vtdQ0f-UP8RxUtopo9D_1v') },
    { id: 'tenbihat-14', name: 'ተንቢሃት ደርስ 14.mp3', type: 'audio', url: getDirectLink('1sFVRb7PpABRIl9o5cuGwCW14GEjS_V4Z') },
    { id: 'tenbihat-15', name: 'ተንቢሃት ደርስ 15.mp3', type: 'audio', url: getDirectLink('1gyfTmsX9uwuyqzi2SCqLo6v3zWNsTTCf') },
    { id: 'tenbihat-16', name: 'ተንቢሃት ደርስ 16.mp3', type: 'audio', url: getDirectLink('1W3IRtI5YiAxKvOSLWQ-O8EcNfxsEQtne') },
    { id: 'tenbihat-17', name: 'ተንቢሃት ደርስ 17.mp3', type: 'audio', url: getDirectLink('1QWkWpMKD6WLim-83sX_pC0VfuD_So3H2') },
    { id: 'tenbihat-18', name: 'ተንቢሃት ደርስ 18.mp3', type: 'audio', url: getDirectLink('15afFmN51JTOZW2Vkr-trxqdRDMeeFemC') },
    { id: 'tenbihat-19', name: 'ተንቢሃት ደርስ 19.mp3', type: 'audio', url: getDirectLink('1GEAwt1Tih2a7uDRj3uKwXGgJYOI_KKmt') },
    { id: 'tenbihat-20', name: 'ተንቢሃት ደርስ 20.mp3', type: 'audio', url: getDirectLink('1-bl9ddnY5-re8gNphEIjDXoqhgvCCf_9') },
    { id: 'tenbihat-21', name: 'ተንቢሃት ደርስ 21.mp3', type: 'audio', url: getDirectLink('1ON8rlYUJ1UxFdUlbVejUWtnbBHFbJ286') },
    { id: 'tenbihat-22', name: 'ተንቢሃት ደርስ 22.mp3', type: 'audio', url: getDirectLink('1aDsb7qlBcrIaj_GbeGY5xUzxiT7O5_0C') },
    { id: 'tenbihat-23', name: 'ተንቢሃት ደርስ 23.mp3', type: 'audio', url: getDirectLink('1j06qBxM1kFL3f1paW_1ZJlxYeHPV0iQf') },
    { id: 'tenbihat-24', name: 'ተንቢሃት ደርስ 24.mp3', type: 'audio', url: getDirectLink('1kYgypIxhJpKQXkBPExuE4sCE-UW16KFN') },
    { id: 'tenbihat-25', name: 'ተንቢሃት ደርስ 25.mp3', type: 'audio', url: getDirectLink('1aJnx2Pu6TISo8gEyWMYWQYXxYs57aaZJ') },
    { id: 'tenbihat-26', name: 'ተንቢሃት ደርስ 26.mp3', type: 'audio', url: getDirectLink('1iCr30KlucTu59hGYiUu703RYJOsXjwX9') },
    { id: 'tenbihat-27', name: 'ተንቢሃት ደርስ 27.mp3', type: 'audio', url: getDirectLink('1dv6lLC9w0gnXp0n7KNce43qG1Zaw4GHu') },
    { id: 'tenbihat-28', name: 'ተንቢሃት ደርስ 28.mp3', type: 'audio', url: getDirectLink('1nZs96_U0ujrof82I-tGYc4L0hznjYc_v') },
    // Index 29 was empty
    { id: 'tenbihat-30', name: 'ተንቢሃት ደርስ 30.mp3', type: 'audio', url: getDirectLink('1MDall2mOzaaaD79-7jQG0Ta55li1hWvF') },
    { id: 'tenbihat-31', name: 'ተንቢሃት ደርስ 31.mp3', type: 'audio', url: getDirectLink('17oAEZj4N_PuVUjBHNJrb73QeNSiZU5xl') },
    { id: 'tenbihat-32', name: 'ተንቢሃት ደርስ 32.mp3', type: 'audio', url: getDirectLink('1Gi43ZCCY3R4e2G1yVr3IbjsWJbcG2yb0') },
    { id: 'tenbihat-33', name: 'ተንቢሃት ደርስ 33.mp3', type: 'audio', url: getDirectLink('1pAft01bdCLKkgNdHSdo6d1ZhrnY7Gc0r') },
    { id: 'tenbihat-34', name: 'ተንቢሃት ደርስ 34.mp3', type: 'audio', url: getDirectLink('1U2blflhDxBd-M5CJU-rtAl6hff1X5ArX') },
    { id: 'tenbihat-35', name: 'ተንቢሃት ደርስ 35.mp3', type: 'audio', url: getDirectLink('1d_sQzs1KCmPDEjcrqgDMPmpJYItpUwGR') },
    { id: 'tenbihat-36', name: 'ተንቢሃት ደርስ 36.mp3', type: 'audio', url: getDirectLink('18YjN7bEEh2DBBjbeFcgPMSvfo2qElHVz') },
    { id: 'tenbihat-37', name: 'ተንቢሃት ደርስ 37.mp3', type: 'audio', url: getDirectLink('16fNAgyq5JVN85kJklFNPNwClOVmE6uya') },
    { id: 'tenbihat-38', name: 'ተንቢሃት ደርስ 38.mp3', type: 'audio', url: getDirectLink('1HCNgNBRiTIuuz7KjK9lVKU4XX6-7Rcwr') },
    { id: 'tenbihat-39', name: 'ተንቢሃት ደርስ 39.mp3', type: 'audio', url: getDirectLink('1wKwK0QXDBLfaVu7ePBixfz3W8gCzwJFu') },
    { id: 'tenbihat-40', name: 'ተንቢሃት ደርስ 40.mp3', type: 'audio', url: getDirectLink('1x0qI51x1YDSOQSJbDYsT8JFv3jIg0QV2') },
    { id: 'tenbihat-41', name: 'ተንቢሃት ደርስ 41.mp3', type: 'audio', url: getDirectLink('14HfhuW0nX4JBiOho7m5THJs_juk2_XOJ') },
    { id: 'tenbihat-42', name: 'ተንቢሃት ደርስ 42.mp3', type: 'audio', url: getDirectLink('1EopbhmLL6EAFkjBB_f-08E9vMDuBhLZZ') },
    { id: 'tenbihat-43', name: 'ተንቢሃት ደርስ 43.mp3', type: 'audio', url: getDirectLink('1zl0ztyELoIBxzeATM6tp16_FSdBIC2MR') },
    { id: 'tenbihat-44', name: 'ተንቢሃት ደርስ 44.mp3', type: 'audio', url: getDirectLink('1R8vVKGkR6sV-gBEqnoB6yLoqmy33zW3c') },
    { id: 'tenbihat-45', name: 'ተንቢሃት ደርስ 45.mp3', type: 'audio', url: getDirectLink('1H_xrIHdvJytYV_7ewQoN75-06jNYbPXt') },
    { id: 'tenbihat-46', name: 'ተንቢሃት ደርስ 46.mp3', type: 'audio', url: getDirectLink('1zvdLPL5T_4_6ovOz5S-CEEX8R7HAkAbT') },
    { id: 'tenbihat-47', name: 'ተንቢሃት ደርስ 47.mp3', type: 'audio', url: getDirectLink('1ybQGsIpLY4GilP62BrCWXR1J9M5NRO6s') },
    { id: 'tenbihat-48', name: 'ተንቢሃት ደርስ 48.mp3', type: 'audio', url: getDirectLink('1uG9GRBkWPTnM3MR1WVcnLKyQVFOUn7su') },
    { id: 'tenbihat-49', name: 'ተንቢሃት ደርስ 49.mp3', type: 'audio', url: getDirectLink('1PDXKNWqeS6I6N7kPW2QOqVSK6gbmFImY') },
    { id: 'tenbihat-50', name: 'ተንቢሃት ደርስ 50.mp3', type: 'audio', url: getDirectLink('1UTEOnJrqnGG4eyMQq96zTsWgCzSssELb') },
    { id: 'tenbihat-51', name: 'ተንቢሃት ደርስ 51.mp3', type: 'audio', url: getDirectLink('1FnFxiYDj7n172YfuImEd5Ae87ORiI_V-') },
    { id: 'tenbihat-52', name: 'ተንቢሃት ደርስ 52.mp3', type: 'audio', url: getDirectLink('1Wct1WUzKQRUZVT_Zw5Ll1PIQFJFAefrD') },
    { id: 'tenbihat-53', name: 'ተንቢሃት ደርስ 53.mp3', type: 'audio', url: getDirectLink('1AC24iV0QNz7tMW4W5e_PRG1mKz5Qu1Xz') },
    { id: 'tenbihat-54', name: 'ተንቢሃት ደርስ 54.mp3', type: 'audio', url: getDirectLink('1z7BN1ccNEvyS3O18ZcUy7vCvKbXO85bX') },
    { id: 'tenbihat-55', name: 'ተንቢሃት ደርስ 55.mp3', type: 'audio', url: getDirectLink('13ger2PalpwGQMUf074Z1TdSKhwCxIdXn') },
    { id: 'tenbihat-56', name: 'ተንቢሃት ደርስ 56.mp3', type: 'audio', url: getDirectLink('17Vrm1G6KL3cTgF7dLni9dVMNEFLkjhc_') },
    { id: 'tenbihat-57', name: 'ተንቢሃት ደርስ 57.mp3', type: 'audio', url: getDirectLink('1RzRbzdM6G8QzczADK71RwfRSYsibGWeP') },
    { id: 'tenbihat-58', name: 'ተንቢሃት ደርስ 58.mp3', type: 'audio', url: getDirectLink('16RQamHk-gf02mo6073IVOEB73sYAr8Zj') },
    { id: 'tenbihat-59', name: 'ተንቢሃት ደርስ 59.mp3', type: 'audio', url: getDirectLink('1_HuoKA_fJ6TiFYnfPVkMz2HrzOCrW2N2') },
    { id: 'tenbihat-60', name: 'ተንቢሃት ደርስ 60.mp3', type: 'audio', url: getDirectLink('1zh97CkgDLu9kT394Gy4v-NtRnXsVAYJO') },
    { id: 'tenbihat-61', name: 'ተንቢሃት ደርስ 61.mp3', type: 'audio', url: getDirectLink('1x19LjitjSI-U6fIJtEYLYSVjB72DoZPr') },
    { id: 'tenbihat-62', name: 'ተንቢሃት ደርስ 62.mp3', type: 'audio', url: getDirectLink('19Tno_hWHnlA8mOvu6NgawiTag_KIq2S0') },
    { id: 'tenbihat-63', name: 'ተንቢሃት ደርስ 63.mp3', type: 'audio', url: getDirectLink('1YG1eRaRfYhAkOKUZc8d0m7ySOmJD32fS') },
];
